---
title: "Development actions history"
output: html_document
editor_options: 
  chunk_output_type: console
---

# First time just after creating the project

- Fill the following chunk to create the DESCRIPTION of your package

```{r description, eval=FALSE}
# Describe your package
fusen::fill_description(
  pkg = here::here(),
  fields = list(
    Title = "Aide à la publication sur Agreste",
    Description = "Aide à la création des documents qui, après PAO, pourront être publiés sur Agreste. Facilite la cration de tableaux, graphiques, cartes. Automatise la création des chiffres et données.",
    `Authors@R` = c(
      person("Anaël", "Delorme", email = "anael.delorme@agriculture.gouv.fr", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1122-9076")),
      person("Killian", "Steunou", email = "killian.steunou@agriculture.gouv.fr", role="aut"),
      person(given = "MinAgri-SSP", role = "cph")
    )
  ),
  overwrite = TRUE
)
# Define License with use_*_license()
usethis::use_mit_license("Agreste")
```


# Package development tools

## Use everytime needed

```{r}
# Simulate package installation
pkgload::load_all()

# Generate documentation and deal with dependencies
attachment::att_amend_desc()

# Check the package
devtools::check(error_on = "error")
covr::report()
```

# Share the package

```{r}
# set and try pkgdown documentation website
usethis::use_pkgdown()

detach("package:agreste", unload = TRUE)

options(rmarkdown.html_vignette.check_title = FALSE)
options(pkgdown.internet = FALSE)

pkgdown::build_site(examples = FALSE,
                    lazy = TRUE,
                    preview = TRUE,
                    new_process = TRUE,
                    devel = TRUE)

# build the tar.gz to share with others
devtools::build(binary = TRUE)
```

