---
title: "flat_export_excel.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(openxlsx)
library(assertthat)
library(comprehenr)
library(collections)
```


# Créer les styles des cellules excel

```{r function_creer_liste_style_excel}

#' Parametrer le tableur excel
#' 
#' Cette fonction permet de créer une liste avec tous les styles utiles aux publications Agreste xlsx
#' @param format le format choisi : "chiffres_et_donnees" ou "primeur"
#'
#' @return une liste avec tous les styles disponibles (objets openxls)
#' @export
#' 
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#'
#' @examples
creer_liste_style_excel <- function(format = "chiffres_et_donnees") {
  assert_that((format %in% c("chiffres_et_donnees", "primeur")), msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  
  options("openxlsx.borderStyle" = "thin")
  options("openxlsx.borderColour" = "black")
  options("openxlsx.dateFormat" = "mm/dd/yyyy")
  options("openxlsx.paperSize" = 9)
  options("openxlsx.orientation" = "portrait")
  
  if (format == "chiffres_et_donnees") {
    font <- "Marianne"
  } else if (format == "primeur") {
    font <- "Calibri"
  }
  
  titleStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <- list(titre = titleStyle)
  
  titre_primeur_style <- createStyle(
    fontName = font,
    fontSize = 14,
    fontColour = "#548235",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(titre_primeur = titre_primeur_style))
  
  subtitleStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    textDecoration = "italic",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sous_titre = subtitleStyle))
  
  headerStyle <- switch(
    format,
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      fgFill = "#FF8D7E",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "white",
      halign = "center",
      valign = "center",
      fgFill = "#548235",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(ligne_titre = headerStyle))

  
  dataStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(texte = dataStyleText))
  
  
  dataStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style, values = c(numerique = dataStyleNum))
  
  dataStyleNumDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.0"
  )
  
  liste_style <-
    append(liste_style, values = c(decimal = dataStyleNumDecimal))
  
  
  dataItalicStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(texte_italique = dataItalicStyleText))
  
  
  dataItalicStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_italique = dataItalicStyleNum))
  
  
  dataItalicStyleNumUneDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.0"
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_italique = dataItalicStyleNumUneDecimal))
  
  
  dataTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(texte_total = dataTotalStyleText))
  
  
  dataTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(numerique_total = dataTotalStyleNum))
  
  
  dataTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.0",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_total = dataTotalStyleNumDecimal))
  
  
  dataSubTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(texte_sous_total = dataSubTotalStyleText))
  
  
  
  dataSubTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_sous_total = dataSubTotalStyleNum))
  
  
  dataSubTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.0",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_sous_total = dataSubTotalStyleNumDecimal))
  
  
  dataPrecisionStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 1,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte = dataPrecisionStyleText))
    
  
  dataSectionStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      fgFill = "#c6ddb4",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(texte_section = dataSectionStyleText))
  
  
  noteStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    borderColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <- append(liste_style, values = c(note = noteStyle))
  
  sourceStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(source = sourceStyle))
  
  
  champStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(champ = champStyle))
  
  sommaireSectionStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "left",
    valign = "center",
    fgFill = "#FF8D7E",
    borderColour = "black",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style,
           values = c(sommaire_section = sommaireSectionStyle))
  
  
  sommaireSection2Style <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    indent = 1,
    halign = "left",
    valign = "center",
    fgFill = "#FFE2DB",
    borderColour = "black",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style,
           values = c(sommaire_section2 = sommaireSection2Style))
  
  
  sommaireSheetStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    indent = 3,
    halign = "left",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sommaire_lien = sommaireSheetStyle))
  
  retourSommaireSheetStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "center",
    valign = "center",
    fgFill = "#FF8D7E",
    wrapText = TRUE
  )
  liste_style <-
    append(liste_style,
           values = c(bouton_retour_sommaire = retourSommaireSheetStyle))
  
  return(liste_style)
  
}

```

```{r examples_creer_liste_style_excel, eval=FALSE}
library(agreste)
mes_styles <- creer_liste_style_excel(format = "chiffres_et_donnees")

#exemples
mes_styles$ligne_titre
mes_styles$numerique

```

```{r tests_creer_liste_style_excel}
test_that("L'objet retourné est une liste", {
  expect_true(class(creer_liste_style_excel()) == "list")
})
test_that('Les styles définis sont bien de type "Style"', {
  mes_styles <- creer_liste_style_excel()
  for (st in mes_styles) {
    expect_true(class(st) == "Style")
  }
})
```

```{r function-row_to_add_format}
#' Renvoie le nombre de lignes à ajouter selon le format
#' 
#' @param format CHAR le format choisi entre "chiffres_et_donnees" et "primeur"
#' 
#' @return NUM le nombre de lignes à ajouter
row_to_add_format <- function(format) {
  if (format == "chiffres_et_donnees") {
    return(0)
  } else {
    return(2)
  }
}
```

# Ajouter un tableau Excel

```{r function_ajouter_tableau_excel}
#' Ajouter un tableau dans une feuille excel
#'
#' Cette fonction crée une nouvelle feuille dans le classeur passé en paramètre et y insère un tableau mis en forme.
#'
#' @param classeur workbook créé avec openXLSX
#' @param tableau dataframe ou tibble à insérer dans une nouvelle feuille
#' @param nom_feuille nom de la nouvelle feuille
#' @param ligne_debut la ligne à laquelle démarre le tableau
#' @param col_debut la colonne à laquelle démarre le tableau
#' 
#' @return Rien n'est renvoyé mais l'objet classeur a une nouvelle feuille
#' 
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx writeData
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_tableau_excel <- function(classeur, tableau, nom_feuille, ligne_debut = 3, col_debut = 2) {

  assert_that(class(classeur)=="Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.data.frame(tableau),
              msg = "Le tableau doit \u00eatre un dataframe ou un tibble.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(ligne_debut > 0,
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(ligne_debut),
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  addWorksheet(wb = classeur,
               sheetName = nom_feuille)
  writeData(wb = classeur,
            sheet = nom_feuille,
            x = tableau,
            startCol = col_debut,
            startRow = ligne_debut)
}
```

```{r examples_ajouter_tableau_excel, eval=FALSE}

# Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
# Sauvegarde du classeur
# Ouverture du classeur
library(openxlsx)
library(agreste)
mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel()

start_ligne = 3
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = "iris")
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$ligne_titre, rows = start_ligne, cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 2)
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 3)
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 4)
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal_italique, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 5)
addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$texte, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 6)

start_ligne = 3
start_col = 2
nb_col = ncol(airquality)

ajouter_tableau_excel(classeur = mon_classeur, tableau = airquality, nom_feuille = "airquality")
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$ligne_titre, rows = start_ligne, cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 2)
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 3)
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 4)
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 5)
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 6)
addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 7)

saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)

browseURL("tableau.xlsx")

```

```{r tests_ajouter_tableau_excel}
test_that("mon_classeur fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()

  expect_error(ajouter_tableau_excel(classeur = "iris",
                                     tableau = iris,
                                     nom_feuille = "tab_iris"),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = "tab_iris",
                                     nom_feuille = "tab_iris"),
               "Le tableau doit \u00eatre un dataframe ou un tibble.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = iris,
                                     nom_feuille = iris),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = iris,
                                     nom_feuille = "tab_iris",
                                     ligne_debut = 0,
                                     col_debut = 2),
               "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = iris,
                                     nom_feuille = "tab_iris",
                                     ligne_debut = 3,
                                     col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = iris,
                                     nom_feuille = "tab_iris",
                                     ligne_debut = "1",
                                     col_debut = 2),
               "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur,
                                     tableau = iris,
                                     nom_feuille = "tab_iris",
                                     ligne_debut = 3,
                                     col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")

})

test_that("Le tableau ajouté est le même dans le workbook", {
  mon_classeur <- openxlsx::createWorkbook()
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "Iris")
  
  expect_equal(sum(openxlsx::readWorkbook(mon_classeur, colNames = TRUE) == iris), 750)
})

test_that("Les noms de feuille sont les bons", {
  mon_classeur <- openxlsx::createWorkbook()
  for (i in 1:6) {
    ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = paste("Iris", i))
  }
  expect_true(sum(names(mon_classeur) == c("Iris 1", "Iris 2", "Iris 3", "Iris 4", "Iris 5", "Iris 6")) == 6)
  
})

```

# Ajouter le titre d'un primeur

```{r function-ajouter_titre_primeur}
#' Ajouter le titre du primeur dans la première cellule de chaque feuille
#'
#' Cette fonction permet d'ajouter le titre en haut de chaque feuille 
#' d'un classeur de type primeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param titre le titre à ajouter
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_titre_primeur <- function(classeur,
                                  titre,
                                  col_debut = 2,
                                  fusion = TRUE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(titre),
              msg = "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  
  liste_style = creer_liste_style_excel(format = "primeur")
  style_titre_primeur = liste_style$titre_primeur
  
  write_row <- 1 
  
  for (feuille in names(classeur)) {
    if (isTRUE(fusion)) {
      nb_col = ncol(readWorkbook(classeur, sheet = feuille))
      if (!is.null(nb_col)) {
        mergeCells(classeur, feuille, cols = col_debut:(col_debut+nb_col-1), rows = write_row)
      }
    }
    writeData(classeur, feuille, titre, startCol = col_debut, startRow = write_row)
    addStyle(wb = classeur, sheet = feuille, style = style_titre_primeur, rows = write_row, cols = col_debut)
  }
  
  
}
```

```{r examples-ajouter_titre_primeur, eval=FALSE}
library(openxlsx)
library(agreste)
mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel(format = "primeur")

start_ligne = 5
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      ligne_debut = 5)

## Formatage

addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal_italique,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$texte,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 6)

## Ajout du titre 

ajouter_titre_primeur(classeur = mon_classeur,
                      titre = "Iris")

## Sauvegarde
saveWorkbook(wb = mon_classeur,
             file = "tableau.xlsx",
             overwrite = TRUE)

browseURL("tableau.xlsx")
```

```{r tests_ajouter_titre_primeur}
test_that("ajouter_titre_primeur fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")
  titre = "Données iris"
  
  expect_error(ajouter_titre_primeur(classeur = nom_page,
                                     titre = titre),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = iris),
               "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = 2,
                                     fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")

})

test_that("Le titre est le bon dans le workbook", {
  mon_classeur <- openxlsx::createWorkbook()
  titre = "Données iris"
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris, 
                        nom_feuille = "iris",
                        col_debut = 5)
  ajouter_titre_primeur(classeur = mon_classeur,
                        titre = titre)
  expect_true(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[1] == titre)
})

```

# Ajouter un titre

```{r function_ajouter_titre_tableau}
#' Ajouter le titre du tableau dans la première cellule d'une feuille
#'
#' Cette fonction permet d'ajouter un titre dans la cellule A1 d'une feuille
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param titre le titre à ajouter
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_titre_tableau <- function(classeur,
                                  nom_feuille,
                                  titre,
                                  col_debut = 2,
                                  format = "chiffres_et_donnees",
                                  fusion = TRUE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(titre),
              msg = "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(format)=="character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  
  liste_style = agreste::creer_liste_style_excel(format = format)
  style_titre = liste_style$titre
  
  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  write_row <- 1 + row_to_add_format(format = format)
  
  if (isTRUE(fusion)) {
    if (!is.null(nb_col)) {
      mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = write_row )
    }
  }
  writeData(classeur, nom_feuille, titre, startCol = col_debut, startRow = write_row)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_titre, rows = write_row, cols = col_debut)
}

```

```{r examples_ajouter_titre_tableau, eval=FALSE}

library(openxlsx)
library(agreste)

## Création d'un classeur

mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel(format = "chiffres_et_donnees")

start_ligne = 3
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris")

## Formatage

addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal_italique,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$texte,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 6)

## Ajout du titre 

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Données fleurs iris",
                      col_debut = 2,
                      format = "chiffres_et_donnees")

## Deuxième feuille

start_ligne = 3
start_col = 2
nb_col = ncol(airquality)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality")

addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 6)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 7)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Données qualité de l'air",
                      col_debut = 2)

saveWorkbook(wb = mon_classeur,
             file = "tableau.xlsx",
             overwrite = TRUE)

browseURL("tableau.xlsx")

```

```{r tests_ajouter_titre_tableau}
test_that("mon_classeur fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")
  titre = "Données iris"
  
  expect_error(ajouter_titre_tableau(classeur = nom_page,
                                     nom_feuille = "iris",
                                     titre = titre),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "tab_iris",
                                     titre = iris),
               "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = iris,
                                     titre = titre),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "iris",
                                     titre = titre,
                                     col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "iris",
                                     titre = titre,
                                     col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "iris",
                                     titre = titre,
                                     col_debut = 2,
                                     format = 2),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "iris",
                                     titre = titre,
                                     col_debut = 2,
                                     format ="chiffres_et_donnees",
                                     fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")

})

test_that("Le titre est le bon dans le workbook", {
  mon_classeur <- openxlsx::createWorkbook()
  titre = "Données iris"
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris, 
                        nom_feuille = "iris")
  ajouter_titre_tableau(classeur = mon_classeur,
                                     nom_feuille = "iris",
                                     titre = titre,
                                     col_debut = 2,
                                     format ="chiffres_et_donnees",
                                     fusion = TRUE)
  expect_true(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[1] == titre)
})

```

# Ajouter une note de lecture

```{r function_ajouter_note_lecture}
#' Ajouter une note de lecture sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter une note de lecture sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param note la note à écrire
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_note_lecture <- function(classeur,
                                 nom_feuille,
                                 note,
                                 format = "chiffres_et_donnees",
                                 col_debut = 2,
                                 fusion = TRUE,
                                 avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(note),
              msg = "La note doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style <- creer_liste_style_excel(format = format)
  style_note <- style$note
  last_row <- nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_note <- last_row + 2 + nb_row_to_add
    
  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_note)
  }
  writeData(classeur, nom_feuille, paste("Note de lecture :", note), startCol = col_debut, startRow = row_note)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_note, rows = row_note, cols = col_debut)
}
```

```{r examples_ajouter_note_lecture, eval=FALSE}

# Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
# Ajout d'une note de lecture
# Sauvegarde du classeur
# Ouverture du classeur
library(openxlsx)
library(agreste)
mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel()

start_ligne = 3
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris")
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur, 
        sheet = "iris",
        style = mes_styles$decimal_italique,
        rows = (start_ligne+1):(nrow(iris)+start_ligne),
        cols = 5)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$texte,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 6)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Iris",
                      col_debut = start_col,
                      format = "chiffres_et_donnees")

ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "iris",
                     note = "Ceci est une note de lecture",
                     col_debut = 2)

start_ligne = 3
start_col = 2
nb_col = ncol(airquality)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality")

addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 6)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 7)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Données qualité de l'air",
                      col_debut = 2)

ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "airquality",
                     note = "Ceci est une autre note de lecture",
                     col_debut = 2)

saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)

browseURL("tableau.xlsx")

```

```{r tests_ajouter_note_lecture}
test_that("ajouter_note_lecture fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  openxlsx::addWorksheet(mon_classeur, "iris")
  note = "Une note quelconque"
  
  expect_error(ajouter_note_lecture(classeur = note,
                                    nom_feuille = "iris",
                                    note = note),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = iris),
               "La note doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = iris,
                                    note = note),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    format = "info rapide"),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 2,
                                    fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 2,
                                    avec_titre = "oui"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("La note est bien présente dans le workbook et identique à celle rentrée en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  note <- "Note de lecture"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris")
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "iris",
                       note = note,
                       format = "primeur",
                       avec_titre = FALSE)
  
  expect_equal(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[dim(iris)[1]+3], paste("Note de lecture :", note))
})

```

# Ajouter la source

```{r function_ajouter_source}
#' Ajouter la source sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter une source sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param source la source à ajouter
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param avec_note si une note de lecture est présente ou pas, par défaut TRUE
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_source <- function(classeur,
                           nom_feuille,
                           source,
                           format = "chiffres_et_donnees",
                           col_debut = 2,
                           avec_note = TRUE,
                           fusion = TRUE,
                           avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(source),
              msg = "La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_note) == "logical",
              msg = "Le param\u00e8tre avec_note doit \u00eatre TRUE ou FALSE.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style = creer_liste_style_excel(format = format)
  style_source <- style$source
  last_row = nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  if (isTRUE(avec_note)) {
    ligne_de_depart_source = 0
  } else {
    ligne_de_depart_source = 1
  }
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_source <- last_row + ligne_de_depart_source + 1 + nb_row_to_add

  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_source)
  }
  writeData(classeur, nom_feuille, paste("Source :",source), startCol = col_debut, startRow = row_source)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_source, rows = row_source, cols = col_debut)
}
```

```{r examples_ajouter_source, eval=FALSE}

# Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
# Ajout de la source
# Sauvegarde du classeur
# Ouverture du classeur
library(openxlsx)
library(agreste)
mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel()

start_ligne = 3
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris")
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur, 
        sheet = "iris",
        style = mes_styles$decimal_italique,
        rows = (start_ligne+1):(nrow(iris)+start_ligne),
        cols = 5)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$texte,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 6)
ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Iris",
                      col_debut = start_col,
                      format = "chiffres_et_donnees")

ajouter_source(classeur = mon_classeur,
               nom_feuille = "iris",
               source = "Ceci est une source quelconque",
               format = "chiffres_et_donnees",
               col_debut = start_col,
               avec_note = FALSE)

start_ligne = 3
start_col = 2
nb_col = ncol(airquality)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality")

addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 6)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 7)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Données qualité de l'air",
                      col_debut = 2)

ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "airquality",
                     note = "blablabla",
                     col_debut = start_col)
ajouter_source(classeur = mon_classeur,
               nom_feuille = "airquality",
               source = "Eurostat",
               col_debut = start_col,
               avec_note = TRUE)

saveWorkbook(wb = mon_classeur,
             file = "tableau.xlsx",
             overwrite = TRUE)

browseURL("tableau.xlsx")

```

```{r tests_ajouter_source}
test_that("ajouter_source fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  ajouter_tableau_excel(classeur = mon_classeur, 
                        nom_feuille = "iris",
                        tableau = iris)
  source = "Une note quelconque"
  expect_error(ajouter_source(classeur = source,
                              nom_feuille = "iris",
                              source = source,
                              avec_note = FALSE),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = iris,
                              avec_note = FALSE),
               "La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = iris,
                              source = source,
                              avec_note = FALSE),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              format = "info rapide",
                              avec_note = FALSE),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = "2",
                              avec_note = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 0,
                              avec_note = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = "oui",
                              avec_note = FALSE),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = TRUE,
                              avec_note = "non"),
               "Le param\u00e8tre avec_note doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = TRUE,
                              avec_note = FALSE,
                              avec_titre = "non"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("La source est bien présente dans le workbook et identique à celle rentrée en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  note <- "Une note de lecture"
  source <- "Une source quelconque"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris",
                        col_debut = 5)
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "iris",
                       note = note, 
                       format = "primeur",
                       avec_titre = FALSE)
  ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = source,
                 format = "primeur",
                 avec_note = TRUE,
                 avec_titre = FALSE)
  
  expect_equal(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[dim(iris)[1]+4], paste("Source :", source))
})

```

# Ajouter le champ

```{r function_ajouter_champ}
#' Ajouter le champ sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter un champ sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param champ le champ à ajouter
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
ajouter_champ <- function(classeur,
                          nom_feuille,
                          champ,
                          format = "chiffres_et_donnees",
                          col_debut = 2,
                          fusion = TRUE,
                          avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(champ),
              msg = "Le champ doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style <- creer_liste_style_excel(format = format)
  style_champ <- style$champ
  last_row <- nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_champ <- last_row + 1 + nb_row_to_add

  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_champ)
  }
  writeData(classeur, nom_feuille, paste("Champ :",champ), startCol = col_debut, startRow = row_champ)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_champ, rows = row_champ, cols = col_debut)
}
```

```{r examples_ajouter_champ, eval=FALSE}

# Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
# Ajout du champ
# Sauvegarde du classeur
# Ouverture du classeur
library(openxlsx)
library(agreste)
mon_classeur <- createWorkbook()

mes_styles <- creer_liste_style_excel(format = "chiffres_et_donnees")

start_ligne = 3
start_col = 2
nb_col = ncol(iris)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris")
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur, 
        sheet = "iris",
        style = mes_styles$decimal_italique,
        rows = (start_ligne+1):(nrow(iris)+start_ligne),
        cols = 5)
addStyle(wb = mon_classeur,
         sheet = "iris",
         style = mes_styles$texte,
         rows = (start_ligne+1):(nrow(iris)+start_ligne),
         cols = 6)
ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Iris",
                      col_debut = start_col,
                      format = "chiffres_et_donnees")

ajouter_source(classeur = mon_classeur,
               nom_feuille = "iris",
               source = "Ceci est une source quelconque",
               col_debut = start_col,
               avec_note = FALSE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "iris",
              champ = "France métropolitaine",
              col_debut = start_col)

start_ligne = 3
start_col = 2
nb_col = ncol(airquality)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality")

addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$ligne_titre,
         rows = start_ligne,
         cols = start_col:(nb_col+start_col-1))
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 2)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 3)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$decimal,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 4)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 5)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 6)
addStyle(wb = mon_classeur,
         sheet = "airquality",
         style = mes_styles$numerique,
         rows = (start_ligne+1):(nrow(airquality)+start_ligne),
         cols = 7)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Qualité de l'air",
                      col_debut = start_col)
ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "airquality",
                     note = "blablabla",
                     col_debut = start_col)
ajouter_source(classeur = mon_classeur,
               nom_feuille = "airquality",
               source = "Eurostat",
               col_debut = start_col,
               avec_note = TRUE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "airquality",
              champ = "Daily air quality measurements in New York, May to September 1973.",
              col_debut = start_col)


saveWorkbook(wb = mon_classeur,
             file = "tableau.xlsx",
             overwrite = TRUE)

browseURL("tableau.xlsx")

```

```{r tests_ajouter_champ}
test_that("ajouter_champ fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  ajouter_tableau_excel(classeur = mon_classeur, 
                        nom_feuille = "iris",
                        tableau = iris)
  champ = "Un champ de blé"
  
  expect_error(ajouter_champ(classeur = champ,
                                    nom_feuille = "iris",
                                    champ = champ),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = iris),
               "Le champ doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = iris,
                                    champ = champ),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    format = "info rapide"),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = 2,
                                    fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                             nom_feuille = "iris",
                             champ = champ,
                             col_debut = 2,
                             fusion = TRUE,
                             avec_titre = "non"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("Le champ est bien présent dans le workbook et identique à celui rentré en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  champ <- "Un champ de blé"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris",
                        ligne_debut = 5)
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Agreste",
                 format = "primeur",
                 avec_titre = FALSE)
  ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = champ,
                format = "primeur",
                avec_titre = FALSE)
  
  
  expect_equal(openxlsx::readWorkbook(mon_classeur,
                                      colNames = FALSE,
                                      skipEmptyRows = FALSE)$X1[dim(iris)[1]+5],
               paste("Champ :",
                     champ))
})

```


# Geler des lignes ou colonnes

```{r function-geler}
#' Geler une(des) ligne(s) et/ou une(des) colonne(s) 
#'
#' Cette fonction permet de geler une ou plusieurs lignes ainsi qu'une ou plusieurs colonnes d'une feuille de classeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param ligne la ligne à geler (0 si pas de ligne à geler)
#' @param col la colonne à geler (0 si pas de colonne à geler)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx freezePane
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
geler <- function(classeur,
                  nom_feuille,
                  ligne = 0,
                  col = 0) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(ligne >= 0,
              msg = "La ligne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(col >= 0,
              msg = "La colonne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(is.numeric(ligne),
              msg = "La ligne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(is.numeric(col),
              msg = "La colonne \u00e0 geler doit \u00eatre un entier positif.")
  
  ligne <- ligne + 1
  col <- col + 1
  
  freezePane(classeur, nom_feuille, firstActiveRow = ligne, firstActiveCol = col)

}
```

```{r examples-geler, eval=FALSE}

library(openxlsx)
library(agreste)

# Création d'un classeur avec une feuille contenant iris 
mon_classeur <- createWorkbook()
ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = "iris", ligne_debut = 3, col_debut = 2)

# gel 
geler(mon_classeur, "iris", ligne = 3, col = 1)

# Sauver le classeur
saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
# ouverture
browseURL("tableau.xlsx")
```

```{r tests-geler}
test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")

  expect_error(geler(classeur = nom_page, nom_feuille = "iris"),"Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = iris),"Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = "iris", ligne = "1"),"La ligne \u00e0 geler doit \u00eatre un entier positif.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = "iris", ligne = 1, col = "2"),"La colonne \u00e0 geler doit \u00eatre un entier positif.")
})
```

# Appliquer une taille de colonne

```{r function-taille_colonnes}
#' Applique des tailles de colonne aux tableaux d'un workbook
#'
#' Cette fonction permet d'appliquer une taille de colonne choisie par 
#' l'utilisateur ou bien automatiquement, 
#' le total étant égal à 89, et les colonnes de texte étant plus larges 
#' que les autres en mode automatique
#'
#' @param classeur Le classeur excel, objet de type workbook
#' @param liste_type_donnees LIST liste de vecteurs contenant 
#' les types de données de chaque colonne
#' @param largeurs LIST liste de vecteurs contenant les largeurs colonne, 
#' "auto" pour appliquer des largeurs automatique
#' @param col_debut La colonne à laquelle commencent les tableaux, par défaut 2
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom assertthat assert_that
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx setColWidths
#' @importFrom comprehenr to_vec
#' @importFrom collections dict
#' 
#' @export
#'
#' @examples
taille_colonnes <- function(classeur, liste_type_donnees, largeurs, col_debut = 2) {
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  assert_that(class(liste_type_donnees[[1]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  sheets <- names(classeur)
  
  indice_feuille <- 0
  
  pao_max <- 89
  weight_num <- 2
  
  for (sheet in sheets) {
    nb_col <- ncol(readWorkbook(classeur, sheet = sheet))
    indice_feuille <- indice_feuille + 1
    if (largeurs[[indice_feuille]][1] == "auto") {
      types <- liste_type_donnees[[indice_feuille]]
      mean_width <- pao_max/nb_col
      nb_text <- sum(to_vec(for(type in types) if(type == "texte") 1))
      nb_num <- nb_col - nb_text
      text_width <- mean_width + nb_num*weight_num/nb_text
      if ("texte" %in% types) {
        num_width <- mean_width - weight_num
      } else {
        num_width <- mean_width
      }
      
      d <- dict(keys = c("texte", "decimal", "numerique"),
                items = c(text_width, num_width, num_width))
      
      widths <- to_vec(for(type in types) d$get(type))
    } else {
      widths <- largeurs[[indice_feuille]]
    }
    
    assert_that(sum(widths) <= pao_max,
                msg = paste("La largeur du tableau ne doit pas dépasser ",
                            pao_max,
                            ". Largeur actuelle : ",
                            sum(widths), sep = ""))
    setColWidths(wb = classeur,
                 sheet = sheet,
                 cols = col_debut:(nb_col + col_debut - 1),
                 widths = widths)
  }
  
}
```

```{r examples-taille_colonne, eval=FALSE}
library(openxlsx)
library(agreste)

## Création d'un classeur avec deux feuilles et deux tableaux
mon_classeur <- createWorkbook()

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      ligne_debut = 5,
                      col_debut = 2)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Données fleurs iris",
                      col_debut = 2,
                      format = "primeur")
ajouter_source(classeur = mon_classeur,
               nom_feuille = "iris",
               source = "Ceci est une source quelconque",
               format = "primeur",
               col_debut = 2,
               avec_note = FALSE,
               avec_titre = FALSE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "iris",
              champ = "France métropolitaine",
              format = "primeur",
              col_debut = 2,
              avec_titre = FALSE)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality",
                      ligne_debut = 5,
                      col_debut = 2)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Données qualité de l'air",
                      col_debut = 2,
                      format = "primeur")
ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "airquality",
                     note = "blablabla",
                     format = "primeur",
                     col_debut = 2,
                     avec_titre = FALSE)
ajouter_source(classeur = mon_classeur,
               nom_feuille = "airquality",
               source = "Eurostat",
               format = "primeur",
               col_debut = 2,
               avec_note = TRUE,
               avec_titre = FALSE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "airquality",
              champ = "Daily air quality measurements in New York, May to September 1973.",
              format = "primeur",
              col_debut = 2,
              avec_titre = FALSE)

ajouter_titre_primeur(classeur = mon_classeur,
                      titre = "Exemple 2022")

taille_colonnes(classeur = mon_classeur,
                liste_type_donnees = list(c("decimal",
                                            "decimal",
                                            "decimal",
                                            "decimal",
                                            "texte"),
                                          c("numerique",
                                            "numerique",
                                            "decimal",
                                            "numerique",
                                            "numerique",
                                            "numerique")),
                largeurs = list(c("auto"), c("auto")),
                col_debut = 2)


## Sauver
saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)

## Ouvrir
browseURL("tableau.xlsx")
```

# Formater un workbook automatiquement

```{r function-formater_auto}
#' Formater un classeur entier
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi
#'
#' @param classeur workbook créé avec openXLSX
#' @param format CHAR le type de publication : 
#' "chiffres_et_donnees" ou "primeur"
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque 
#' feuille avec une note de lecture
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre VECTOR vecteur des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
formater_auto <- function(classeur,
                          format,
                          liste_feuilles_avec_note,
                          liste_type_donnees,
                          liste_lignes_titre,
                          liste_lignes_section,
                          liste_lignes_sous_total,
                          liste_lignes_precision,
                          liste_lignes_total,
                          col_debut = 2,
                          avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  
  assert_that(class(liste_feuilles_avec_note) == "character",
              msg = "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
  for (feuille in liste_feuilles_avec_note) {
    assert_that(feuille %in% names(classeur),
                msg = paste("La feuille", feuille, "n'est pas une feuille existante."))
  }
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  for(i in 1:length(liste_type_donnees)) {
    assert_that(class(liste_type_donnees[[i]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  }
  assert_that(class(liste_lignes_titre) == "numeric",
              msg = "La liste des lignes de titre doit \u00eatre un vecteur de nombres entiers.")
  assert_that(class(liste_lignes_section) == "list",
              msg = "La liste des lignes de section doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_section[[i]]) == "numeric",
              msg = "La liste des lignes de section doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_sous_total) == "list",
              msg = "La liste des lignes de sous-total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_sous_total)) {
    assert_that(class(liste_lignes_sous_total[[i]]) == "numeric",
              msg = "La liste des lignes de sous-total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_precision) == "list",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_precision[[i]]) == "numeric",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_total) == "list",
              msg = "La liste des lignes de total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_total)) {
    assert_that(class(liste_lignes_total[[i]]) == "numeric",
              msg = "La liste des lignes de total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  mes_styles <- creer_liste_style_excel(format = format)
  
  nb_row_to_add <- row_to_add_format(format = format)
  
  formater(classeur = classeur, 
           start_row_tabs = 3 + nb_row_to_add, 
           styles = mes_styles,
           liste_feuilles_avec_note = liste_feuilles_avec_note, 
           liste_type_donnees = liste_type_donnees,
           liste_lignes_titre = liste_lignes_titre,
           liste_lignes_section = liste_lignes_section,
           liste_lignes_sous_total = liste_lignes_sous_total,
           liste_lignes_precision = liste_lignes_precision,
           liste_lignes_total = liste_lignes_total,
           col_debut = col_debut,
           format = format,
           avec_titre = avec_titre)
}
```

```{r examples-formater_auto, eval=FALSE}
library(openxlsx)
library(agreste)

## Création d'un classeur avec deux feuilles et deux tableaux
mon_classeur <- createWorkbook()

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      ligne_debut = 5,
                      col_debut = 2)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "iris",
                      titre = "Données fleurs iris",
                      col_debut = 2,
                      format = "primeur")
ajouter_source(classeur = mon_classeur,
               nom_feuille = "iris",
               source = "Ceci est une source quelconque",
               format = "primeur",
               col_debut = 2,
               avec_note = FALSE,
               avec_titre = FALSE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "iris",
              champ = "France métropolitaine",
              format = "primeur",
              col_debut = 2,
              avec_titre = FALSE)

ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = airquality,
                      nom_feuille = "airquality",
                      ligne_debut = 5,
                      col_debut = 2)

ajouter_titre_tableau(classeur = mon_classeur,
                      nom_feuille = "airquality",
                      titre = "Données qualité de l'air",
                      col_debut = 2,
                      format = "primeur")
ajouter_note_lecture(classeur = mon_classeur,
                     nom_feuille = "airquality",
                     note = "blablabla",
                     format = "primeur",
                     col_debut = 2,
                     avec_titre = FALSE)
ajouter_source(classeur = mon_classeur,
               nom_feuille = "airquality",
               source = "Eurostat",
               format = "primeur",
               col_debut = 2,
               avec_note = TRUE,
               avec_titre = FALSE)
ajouter_champ(classeur = mon_classeur,
              nom_feuille = "airquality",
              champ = "Daily air quality measurements in New York, May to September 1973.",
              format = "primeur",
              col_debut = 2,
              avec_titre = FALSE)

ajouter_titre_primeur(classeur = mon_classeur,
                      titre = "Exemple 2022")

taille_colonnes(classeur = mon_classeur,
                liste_type_donnees = list(c("decimal",
                                            "decimal",
                                            "decimal",
                                            "decimal",
                                            "texte"),
                                          c("numerique",
                                            "numerique",
                                            "decimal",
                                            "numerique",
                                            "numerique",
                                            "numerique")),
                largeurs = list(c("auto"), c("auto")),
                col_debut = 2)

## Formater comme un Primeur
formater_auto(classeur = mon_classeur,
              format = "primeur",
              liste_feuilles_avec_note = c("airquality"),
              liste_type_donnees = list(c("decimal",
                                          "decimal",
                                          "decimal",
                                          "decimal",
                                          "texte"),
                                        c("numerique",
                                          "numerique",
                                          "decimal",
                                          "numerique",
                                          "numerique",
                                          "numerique")), 
              liste_lignes_titre = c(1, 1),
              liste_lignes_section = list(c(5, 9),
                                          c(3, 8)),
              liste_lignes_sous_total = list(c(4, 8),
                                             c(2, 7)),
              liste_lignes_precision = list(c(2,3),
                                            c(0)),
              liste_lignes_total = list(c(150),
                                        c(100)),
              col_debut = 2,
              avec_titre = TRUE)

## Sauver
saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)

## Ouvrir
browseURL("tableau.xlsx")

```

```{r tests-formater_auto}
test_that("mon_classeur fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données fleurs iris",
                        col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Ceci est une source quelconque",
                 col_debut = 2,
                 avec_note = FALSE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = "France métropolitaine",
                col_debut = 2)

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = airquality,
                        nom_feuille = "airquality",
                        col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "airquality",
                        titre = "Données qualité de l'air",
                        col_debut = 2)
  agreste::ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "airquality",
                       note = "blablabla",
                       col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "airquality",
                 source = "Eurostat",
                 col_debut = 2,
                 avec_note = TRUE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "airquality",
                champ = "Daily air quality measurements in New York, May to September 1973.",
                col_debut = 2)


  expect_error(formater_auto(classeur = "workbook",
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("airquality"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100))),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = 2,
                             liste_feuilles_avec_note = c("airquality"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100))),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c(1,2,3),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100))),
               "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("feuille 1"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100))),
               "La feuille feuille 1 n'est pas une feuille existante.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("airquality"),
                             liste_type_donnees = c("decimal",
                                                    "decimal",
                                                    "decimal",
                                                    "decimal",
                                                    "texte"),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100))),
               "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("airquality"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100)),
                             col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("airquality"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"),
                                                       c("numerique",
                                                         "numerique",
                                                         "decimal",
                                                         "numerique",
                                                         "numerique",
                                                         "numerique")),
                             liste_lignes_titre = c(1, 1),
                             liste_lignes_section = list(c(5, 9),
                                                          c(3, 8)),
                             liste_lignes_sous_total = list(c(4, 8),
                                                             c(2, 7)),
                             liste_lignes_precision = list(c(2,3),
                                                            c(0)),
                             liste_lignes_total = list(c(150),
                                                        c(100)),
                             col_debut = 2,
                             avec_titre = "non"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")

})

test_that("Le classeur est bien modifié pour un c&d", {
  mon_classeur <- openxlsx::createWorkbook()

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données fleurs iris",
                        col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Ceci est une source quelconque",
                 col_debut = 2,
                 avec_note = FALSE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = "France métropolitaine",
                col_debut = 2)

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = airquality,
                        nom_feuille = "airquality",
                        col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "airquality",
                        titre = "Données qualité de l'air",
                        col_debut = 2)
  agreste::ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "airquality",
                       note = "blablabla",
                       col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "airquality",
                 source = "Eurostat",
                 col_debut = 2,
                 avec_note = TRUE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "airquality",
                champ = "Daily air quality measurements in New York, May to September 1973.",
                col_debut = 2)
  
  expect_equal(length(openxlsx::getStyles(mon_classeur)), 7)
  
  formater_auto(classeur = mon_classeur,
                format = "chiffres_et_donnees",
                liste_feuilles_avec_note = c("airquality"),
                liste_type_donnees = list(c("decimal",
                                            "decimal",
                                            "decimal",
                                            "decimal",
                                            "texte"),
                                           c("numerique",
                                             "numerique",
                                             "decimal",
                                             "numerique",
                                             "numerique",
                                             "numerique")),
                 liste_lignes_titre = c(1, 1),
                 liste_lignes_section = list(c(5, 9),
                                              c(3, 8)),
                 liste_lignes_sous_total = list(c(4, 8),
                                                 c(2, 7)),
                 liste_lignes_precision = list(c(2,3),
                                                c(0)),
                 liste_lignes_total = list(c(150),
                                            c(100)))
  expect_equal(length(openxlsx::getStyles(mon_classeur)), 71)
})

test_that("Le classeur est bien modifié pour un primeur", {
  mon_classeur <- openxlsx::createWorkbook()

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      col_debut = 2,
                      ligne_debut = 5)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données fleurs iris",
                        col_debut = 2,
                        format = "primeur")
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Ceci est une source quelconque",
                 col_debut = 2,
                 avec_note = FALSE,
                 format = "primeur",
                 avec_titre = FALSE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = "France métropolitaine",
                col_debut = 2,
                format = "primeur",
                avec_titre = FALSE)

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = airquality,
                        nom_feuille = "airquality",
                        col_debut = 2,
                        ligne_debut = 5)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "airquality",
                        titre = "Données qualité de l'air",
                        col_debut = 2,
                        format = "primeur")
  agreste::ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "airquality",
                       note = "blablabla",
                       col_debut = 2,
                       format = "primeur")
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "airquality",
                 source = "Eurostat",
                 col_debut = 2,
                 avec_note = TRUE,
                 format = "primeur")
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "airquality",
                champ = "Daily air quality measurements in New York, May to September 1973.",
                col_debut = 2,
                format = "primeur")
  agreste::ajouter_titre_primeur(classeur = mon_classeur,
                                 titre = "Exemple")
  
  expect_equal(length(openxlsx::getStyles(mon_classeur)), 9)
  
  formater_auto(classeur = mon_classeur,
                format = "primeur",
                liste_feuilles_avec_note = c("airquality"),
                liste_type_donnees = list(c("decimal",
                                            "decimal",
                                            "decimal",
                                            "decimal",
                                            "texte"),
                                           c("numerique",
                                             "numerique",
                                             "decimal",
                                             "numerique",
                                             "numerique",
                                             "numerique")),
                 liste_lignes_titre = c(1, 1),
                 liste_lignes_section = list(c(5, 9),
                                              c(3, 8)),
                 liste_lignes_sous_total = list(c(4, 8),
                                                 c(2, 7)),
                 liste_lignes_precision = list(c(2,3),
                                                c(0)),
                 liste_lignes_total = list(c(150),
                                            c(100)))
  expect_equal(length(openxlsx::getStyles(mon_classeur)), 76)
})
```

```{r function-formater}
#' Formater un classeur 
#'
#' @param classeur workbook créé avec openXLSX
#' @param start_row_tabs la ligne de départ des tableaux
#' @param styles une liste de Styles
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque feuille 
#' avec une note de lecture
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre VECTOR vecteur des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param format CHAR le format entre "chiffres_et_donnees" ou "primeur"
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
formater <- function(classeur,
                     start_row_tabs,
                     styles,
                     liste_feuilles_avec_note,
                     liste_type_donnees,
                     liste_lignes_titre,
                     liste_lignes_section,
                     liste_lignes_sous_total,
                     liste_lignes_precision,
                     liste_lignes_total,
                     format,
                     col_debut = 2,
                     avec_titre = FALSE) {
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  style_section <- styles$texte_section
  style_precision <- styles$precision_texte
  i <- 0
  for (feuille in names(classeur)) {
    i <- i + 1
    nb_col <- ncol(readWorkbook(classeur, sheet = feuille))
    last_row <- nrow(readWorkbook(classeur, sheet = feuille, skipEmptyRows = FALSE, colNames = FALSE))
    if (feuille %in% liste_feuilles_avec_note) {
      eff_last_row <- last_row - 4 + nb_row_to_add
    } else {
      eff_last_row <- last_row - 3 + nb_row_to_add
    }
    addStyle(wb = classeur,
             sheet = feuille,
             style = styles$ligne_titre,
             rows = start_row_tabs + liste_lignes_titre[i] - 1,
             cols = col_debut:(nb_col + col_debut - 1))
  
    for (num_col in col_debut:(nb_col + col_debut - 1)) {
      j <- num_col - col_debut + 1
  
      assert_that(liste_type_donnees[[i]][j] %in% c("texte", "numerique", "decimal"),
                  msg = paste("Format de donn\u00e9es", liste_type_donnees[[i]][j], "non valide."))
  
      style_data <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte,
        "numerique" = styles$numerique,
        "decimal" = styles$decimal
      )
      style_sous_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_sous_total,
        "numerique" = styles$numerique_sous_total,
        "decimal" = styles$decimal_sous_total
      )
      style_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_total,
        "numerique" = styles$numerique_total,
        "decimal" = styles$decimal_total
      )
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_data,
               rows = (start_row_tabs + 1):eff_last_row,
               cols = num_col,
               stack = TRUE)
      if (!(0 %in% liste_lignes_sous_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_sous_total,
               rows = liste_lignes_sous_total[[i]] + start_row_tabs,
               cols = num_col,
               stack = TRUE)
      }
      
      if (!(0 %in% liste_lignes_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_total,
               rows = liste_lignes_total[[i]] + start_row_tabs,
               cols = num_col,
               stack = TRUE)
      }
      
    }
    
    addStyle(wb = classeur,
             sheet = feuille,
             style = createStyle(border = "bottom",
                                 borderColour = "black"),
             rows = eff_last_row,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
    
    if (!(0 %in% liste_lignes_precision[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision,
               rows = liste_lignes_precision[[i]] + start_row_tabs,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_section[[i]])) {
      for (row_n in liste_lignes_section[[i]] + start_row_tabs) {
        for (col_n in col_debut:(nb_col + col_debut - 1)) {
          addStyle(wb = classeur,
               sheet = feuille,
               style = style_section,
               rows = row_n,
               cols = col_n,
               stack = TRUE)
        }
      }
      
      for (merge_row in liste_lignes_section[[i]]) {
        mergeCells(wb = classeur,
                 sheet = feuille,
                 cols = col_debut:(nb_col + col_debut - 1),
                 rows = merge_row + start_row_tabs)
      }
      
    }
    
    }
}
```

# Créer un tableau excel formaté depuis un plan

```{r function-creer_excel_depuis_plan}
#' Crée un classeur et le formate
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi, simplement à partir d'un plan. Les fichiers indiqués dans le plan doivent être dans le répertoire de travail.
#'
#' @param plan fichier .xlsx ou data frame contenant les détails pour chaque tableau 
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur"
#' @param type_virgule CHAR le type de séparation décimale utilisée : "." ou ","
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param save LGL TRUE si export du classeur au format xlsx
#' @param path CHAR chemin vers le tableau à sauvegarder
#'
#' @return un objet de type workbook formaté
#' 
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' @importFrom openxlsx read.xlsx
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx saveWorkbook
#' @importFrom openxlsx write.xlsx
#' @importFrom stringr str_trim
#' 
#' @export
#'
#' @examples
creer_excel_depuis_plan <- function(plan,
                                    format,
                                    type_virgule = ",",
                                    col_debut,
                                    save = TRUE,
                                    path = "tableau1.xlsx") {
  
  assert_that(class(plan) %in% c("character", "data.frame"),
              msg = "Le plan doit \u00eatre une cha\u00eene de caract\u00e8res ou un data frame.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(type_virgule %in% c(",", "."),
              msg = 'Le type de virgule doit \u00eatre "." ou ","')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(save) == "logical",
              msg = "save doit \u00eatre TRUE ou FALSE")
  assert_that(class(path) == "character",
              msg = "Le chemin du fichier \u00e0 sauvegarder doit \u00eatre une cha\u00eene de caract\u00e8res.")
  
  if (class(plan) == "character") {
    plan = read.xlsx(plan,
                     colNames = TRUE,
                     rowNames = FALSE)
  }
  i <- 0
  for (liste in plan$Type_colonnes) {
    i <- i + 1
    test_list <- strsplit(liste,
                     split = ", ")[[1]]
    for (type in test_list) {
      assert_that(type %in% c("decimal", "texte", "numerique"),
                  msg = paste("Problème dans la colonne Type_colonnes, tableau ", i, ". Veuillez la vérifier.", sep = ""))
    }
  }
  
  plan[,12:18][is.na(plan[,12:18])] <- 0
  
  nb_tab = nrow(plan)
  
  ligne_debut <- 3 + row_to_add_format(format = format)
  
  liste_feuilles_note <- c()
  liste_data_types <- list()
  liste_lignes_titre <- c()
  liste_lignes_section <- list()
  liste_lignes_sous_total <- list()
  liste_lignes_precision <- list()
  liste_lignes_total <- list()
  liste_col_widths <- list()
  
  
  titre_doc = plan$Titre_document[1]
  
  wb = createWorkbook()
  
  for (tab in 1:nb_tab) {
    filename <- paste(plan$Nom_fichier[tab],
                      plan$Type[tab],
                      sep = ".")
    data <- read.csv(filename,
                     header = TRUE,
                     check.names = FALSE,
                     dec = type_virgule)
    feuille <- plan$Nom_feuille[tab]
    titre <- plan$Titre[tab]
    if (str_trim(plan$Note_de_lecture[tab]) == "" | is.na(plan$Note_de_lecture[tab])) {
      avec_note <- FALSE
    } else {
      avec_note <- TRUE
    }
    source <- plan$Source[tab]
    champ <- plan$Champ[tab]
    if (str_trim(plan$Taille_colonnes[tab]) == "auto") {
      liste_col_widths <- append(liste_col_widths, "auto")
    } else {
      liste_col_widths <- append(liste_col_widths,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Taille_colonnes[tab]), split = ", ")))))
    }
    liste_data_types <- append(liste_data_types,
                               strsplit(plan$Type_colonnes[tab],
                                        split = ", "))
    liste_lignes_titre <- append(liste_lignes_titre,
                                 as.numeric(unlist(strsplit(str_trim(plan$Lignes_titre[tab]), split = ", "))))
    liste_lignes_section <- append(liste_lignes_section,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_section[tab]), split = ", ")))))
    liste_lignes_sous_total <- append(liste_lignes_sous_total,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_sous_total[tab]), split = ", ")))))
    liste_lignes_precision <- append(liste_lignes_precision,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_precision[tab]), split = ", ")))))
    liste_lignes_total <- append(liste_lignes_total,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_total[tab]), split = ", ")))))
    
    agreste::ajouter_tableau_excel(classeur = wb,
                                   tableau = data,
                                   nom_feuille = feuille,
                                   ligne_debut = ligne_debut,
                                   col_debut = col_debut)
    
    agreste::ajouter_titre_tableau(classeur = wb,
                                   nom_feuille = feuille,
                                   titre = titre,
                                   col_debut = col_debut,
                                   format = format)
    if (isTRUE(avec_note)) {
      liste_feuilles_note <- append(liste_feuilles_note, feuille)
      agreste::ajouter_note_lecture(classeur = wb,
                                    nom_feuille = feuille,
                                    note = plan$Note_de_lecture[tab],
                                    col_debut = col_debut,
                                    format = format)
    } 
    
    agreste::ajouter_source(classeur = wb,
                              nom_feuille = feuille,
                              source = source,
                              col_debut = col_debut,
                              avec_note = avec_note,
                              format = format)
    agreste::ajouter_champ(classeur = wb,
                           nom_feuille = feuille,
                           champ = champ,
                           col_debut = col_debut,
                           format = format)
  }
  if (format == "primeur") {
      agreste::ajouter_titre_primeur(classeur = wb,
                                     titre = titre_doc,
                                     col_debut = col_debut,
                                     fusion = TRUE)
  }
  agreste::taille_colonnes(classeur = wb,
                          liste_type_donnees = liste_data_types,
                          largeurs = liste_col_widths,
                          col_debut = col_debut)
  agreste::formater_auto(wb,
                         format = format,
                         liste_feuilles_avec_note = liste_feuilles_note,
                         liste_type_donnees = liste_data_types,
                         liste_lignes_titre = liste_lignes_titre,
                         liste_lignes_section = liste_lignes_section,
                         liste_lignes_sous_total = liste_lignes_sous_total,
                         liste_lignes_precision = liste_lignes_precision,
                         liste_lignes_total = liste_lignes_total,
                         col_debut = col_debut,
                         avec_titre = TRUE)
  if (isTRUE(save)) {
    saveWorkbook(wb, file = path, overwrite = TRUE)
  }
  
  return(wb)
}


```

```{r examples-creer_excel_depuis_plan, eval=FALSE}
library(agreste)
library(dplyr)
library(openxlsx)
### Import du fichier de plan
plan = agreste::modele_plan

### Création des csv 
agreste::resultat_1 %>%
  write.csv(file = "resultat_1.csv", row.names = FALSE)
agreste::resultat_2 %>%
  write.csv(file = "resultat_2.csv", row.names = FALSE)
agreste::resultat_3 %>%
  write.csv(file = "resultat_3.csv", row.names = FALSE)
write.xlsx(plan, "plan.xlsx", row.names = FALSE)
### Formatage
workbook <- creer_excel_depuis_plan(plan = "plan.xlsx",
                                    format = "primeur",
                                    col_debut = 2,
                                    save = TRUE,
                                    path = "document_a_envoyer.xlsx")
browseURL("document_a_envoyer.xlsx")

```

```{r tests-creer_excel_depuis_plan}
test_that("Le formatage se fait correctement et sans erreur", {
  
  plan <- agreste::modele_plan
  
  file1 <- tempfile(pattern = "file", tmpdir = tempdir())
  file2 <- tempfile(pattern = "file", tmpdir = tempdir())
  file3 <- tempfile(pattern = "file", tmpdir = tempdir())
  file_plan <- tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  
  plan$Nom_fichier[1] <- file1
  plan$Nom_fichier[2] <- file2
  plan$Nom_fichier[3] <- file3
  
  openxlsx::write.xlsx(plan, file_plan, row.names = FALSE)
  
  expect_error(agreste::creer_excel_depuis_plan(plan = 1,
                                               format = "primeur",
                                               col_debut = 2,
                                               save = FALSE),
               "Le plan doit \u00eatre une cha\u00eene de caract\u00e8res ou un data frame.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "irapide",
                                               col_debut = 2,
                                               save = FALSE),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = "B",
                                               save = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = "oui"),
               "save doit \u00eatre TRUE ou FALSE")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = plan),
               "Le chemin du fichier \u00e0 sauvegarder doit \u00eatre une cha\u00eene de caract\u00e8res.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = file_plan,
                                               type_virgule = ";"),
               'Le type de virgule doit \u00eatre "." ou ","')
})

test_that("Le classeur est bien modifié pour un c&d", {
  plan <- agreste::modele_plan
  
  file1 <- tempfile(pattern = "file", tmpdir = tempdir())
  file2 <- tempfile(pattern = "file", tmpdir = tempdir())
  file3 <- tempfile(pattern = "file", tmpdir = tempdir())
  file_plan <- tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  
  plan$Nom_fichier[1] <- file1
  plan$Nom_fichier[2] <- file2
  plan$Nom_fichier[3] <- file3
  
  openxlsx::write.xlsx(plan, file_plan, row.names = FALSE)
  
  workbook <- creer_excel_depuis_plan(plan = file_plan,
                                      format = "chiffres_et_donnees",
                                      col_debut = 2,
                                      save = FALSE,
                                      type_virgule = ",")
  expect_true(file.info(file_plan)$size > 0)
  expect_equal(length(names(workbook)),
               3)
  expect_equal(names(workbook),
               agreste::modele_plan$Nom_feuille)
  expect_equal(length(openxlsx::getStyles(workbook)),
               51)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[1])),
               22)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[2])),
               10)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[3])),
               16)
})

test_that("Le classeur est bien modifié pour un primeur", {
  plan <- agreste::modele_plan
  
  file1 <- tempfile(pattern = "file", tmpdir = tempdir())
  file2 <- tempfile(pattern = "file", tmpdir = tempdir())
  file3 <- tempfile(pattern = "file", tmpdir = tempdir())
  file_plan <- tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  
  plan$Nom_fichier[1] <- file1
  plan$Nom_fichier[2] <- file2
  plan$Nom_fichier[3] <- file3
  
  openxlsx::write.xlsx(plan, file_plan, row.names = FALSE)
  
  workbook <- creer_excel_depuis_plan(plan = file_plan,
                                      format = "primeur",
                                      col_debut = 2,
                                      save = TRUE,
                                      path = file_plan,
                                      type_virgule = ",")

  expect_equal(length(names(workbook)),
               3)
  expect_equal(names(workbook),
               agreste::modele_plan$Nom_feuille)
  expect_equal(length(openxlsx::getStyles(workbook)),
               54)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[1])),
               24)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[2])),
               12)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[3])),
               18)
})

```


```{r development-inflate, eval=FALSE}
fusen::inflate(flat_file = "dev/flat_export_excel.Rmd", vignette_name = "Export excel", check=F, overwrite = "yes")
```
