---
title: "flat_appli_format.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(shiny)
```

# Ouvrir l'interface graphique du package

```{r function-app_formatage}
#' Ouvrir l'application Shiny d'édition du tableur
#' 
#' Cette fonction permet d'ouvrir l'interface graphique s'appuyant 
#' sur les fonctions de formatage du package pour éditer des tableaux plus rapidement
#' 
#' @return Rien n'est renvoyé, l'appli s'ouvre.
#' 
#' @importFrom shiny runApp
#' @importFrom shiny shinyAppDir
#' @importFrom shiny fileInput
#' @importFrom shiny shinyApp
#' @importFrom shiny tags
#' @importFrom shiny checkboxInput
#' @importFrom shiny radioButtons
#' @importFrom shiny textInput
#' @importFrom shiny tableOutput
#' @importFrom shiny uiOutput
#' @importFrom shiny actionButton
#' @importFrom shiny req
#' @importFrom shiny renderUI
#' @importFrom shiny selectInput
#' @importFrom shiny observeEvent
#' @importFrom shiny showModal
#' @importFrom shiny removeModal
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyalert shinyalert
#' @importFrom shinyWidgets prettyRadioButtons
#' @importFrom bs4Dash dashboardPage
#' @importFrom bs4Dash dashboardHeader
#' @importFrom bs4Dash dashboardSidebar
#' @importFrom bs4Dash dashboardFooter
#' @importFrom bs4Dash dashboardBody
#' @importFrom magrittr %>%
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx saveWorkbook
#' @importFrom openxlsx removeCellMerge
#' @importFrom openxlsx removeWorksheet
#' 
#' @export
#' 
#' @examples
app_formatage <- function() {
  
  wb <- createWorkbook()
  list_sheets_with_note <- c(" ")
  list_col_data_types <- list()
  index_current_sheet <- 0
  
  wd <- getwd()
  
  ui = dashboardPage(
  skin = "light",
  title = "Mise en forme de tableaux",
  
  header = dashboardHeader(title = "Mise en forme de tableaux"),
  
  sidebar = dashboardSidebar(
    skin = "light",
    
    fileInput(
      inputId = "file1",
      label = "Choisir un fichier CSV",
      multiple = TRUE,
      accept = c("text/csv",
                 "text/comma-separated-values,text/plain",
                 ".csv")),
    
    # Horizontal line ----
    tags$hr(),
    
    # Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
    
    # Input: Select separator ----
    radioButtons("sep", "Separateur",
                 choices = c(Virgule = ",",
                             "Point Virgule" = ";",
                             Tab = "\t"),
                 selected = ","),
    
    # Input: Select quotes ----
    radioButtons("quote", "Guillemets",
                 choices = c(Aucun = "",
                             "Doubles Guillemets" = '"',
                             "Simples Guillemets" = "'"),
                 selected = '"'),
    
    # Horizontal line ----
    tags$hr(),
    
    # Input: Select number of rows to display ----
    radioButtons("disp", "Afficher",
                 choices = c(Head = "head",
                             Tout = "all"),
                 selected = "head"),
    
    radioButtons("virg", "Type de virgule",
                 choices = c(Virgule = ",",
                             Point = "."),
                 selected = ","),
  ),
  # controlbar = dashboardControlbar(),
  footer = dashboardFooter(),
  body = dashboardBody(
    prettyRadioButtons(inputId = "format",
                       label = "Format",
                       choices = c("Chiffres et données" = "chiffres_et_donnees",
                                   Primeur = "primeur"),
                       selected = "chiffres_et_donnees"),
    textInput("feuille", "Nom de la feuille :"),
    textInput("title", "Titre du tableau :"),
    # Output: Data file ----
    tableOutput("contents") %>% withSpinner(),
    uiOutput("deroul"),
    tags$hr(),
    textInput("note", "Note de lecture :"),
    textInput("source", "Source"),
    textInput("champ", "Champ"),
    tags$hr(),
    actionButton("validate", "Valider"),
    textInput("output_file", "Nom du fichier de sortie", value = "output.xlsx"),
    actionButton("enreg", "Enregistrer le fichier Excel")
  ),
  )
  
  server = function(input, output) {
    
    # track_usage(
    #   storage_mode = store_null(console = FALSE),
    #   what = "input"
    # )
    
    options(shiny.maxRequestSize=15*1024^2) # set maximum file size to 15MB
    output$contents <- renderTable({
      
      # input$file1 will be NULL initially. After the user selects
      # and uploads a file, head of that data file by default,
      # or all rows if selected, will be shown.
      
      req(input$file1)
      
      df <- read.csv(input$file1$datapath,
                     header = input$header,
                     sep = input$sep,
                     quote = input$quote,
                     check.names = FALSE,
                     dec = input$virg)
      
      
      if(input$disp == "head") {
        return(head(df, n = 4L))
      }
      else {
        return(df)
      }
      
    })
    
    output$deroul <- renderUI({
      req(input$file1)
      
      df <- read.csv(input$file1$datapath,
                     header = input$header,
                     sep = input$sep,
                     quote = input$quote,
                     check.names = FALSE,
                     dec = input$virg)
      
      lapply(1:ncol(df), function(i) {
        div(style="display: inline-block;vertical-align:top; width: 100px;",
            selectInput(inputId = paste("col_",
                                        as.character(i),
                                        sep = ""),
                        label = paste("Colonne",
                                      as.character(i),
                                      sep = " "),
                        choices = c("Texte" = "texte",
                                    "Entier" = "numerique",
                                    "Décimal" = "decimal")))
      })
    })
    
    observeEvent(input$validate, {
      # print(input$.shinylogs_input$inputs[[(length(input$.shinylogs_input$inputs) - 1)]])
      req(input$file1)
      vec_data_types <- c()
      new_sheet <- TRUE
      df <- read.csv(input$file1$datapath,
                     header = input$header,
                     sep = input$sep,
                     quote = input$quote,
                     check.names = FALSE,
                     dec = input$virg)
      
      for (i in 1:ncol(df)) {
        id <- eval(parse(text = paste("input$col_", as.character(i), sep = "")))
        vec_data_types <- append(vec_data_types, id)
      }
      
      
      df <- read.csv(input$file1$datapath,
                     header = input$header,
                     sep = input$sep,
                     quote = input$quote,
                     check.names = FALSE,
                     dec = input$virg)
      
      if (input$feuille != "" & input$title != "") {
        # showModal(modalDialog("Écriture...", footer = NULL))
        # remove sheet before adding it again (fastest way to clean it)
        if (input$feuille %in% names(wb)) {
          removeWorksheet(wb, input$feuille)
          new_sheet <- FALSE
        } else {
          new_sheet <- TRUE
        }
        start_line <- switch (input$format,
                              "chiffres_et_donnees" = 3,
                              "primeur" = 5
        )
        ajouter_tableau_excel(wb, df, input$feuille, ligne_debut = start_line)
        
        removeCellMerge(wb, input$feuille, 2:(ncol(df)+2-1), 1)
        ajouter_titre_tableau(wb,
                              input$feuille,
                              input$title,
                              fusion = TRUE,
                              format = input$format)
        
        if (input$note != "") {
          list_sheets_with_note <<- append(list_sheets_with_note, input$feuille)
          ajouter_note_lecture(wb, input$feuille, input$note, format = input$format)
          ajouter_source(wb, input$feuille, input$source, avec_note = TRUE, format =input$format)
        } else if (input$source != "") {
          ajouter_source(wb, input$feuille, input$source, avec_note = FALSE, format = input$format)
        }
        if (input$champ != "") {
          ajouter_champ(wb, input$feuille, input$champ, format = input$format)
        }
        
        
        if (isTRUE(new_sheet)) {
          index_current_sheet <<- index_current_sheet + 1
        }
        list_col_data_types[[index_current_sheet]] <<- vec_data_types
        
        # removeModal()
      } else {
        shinyalert("Veuillez indiquer un nom de feuille et de titre avant de valider.", type = "error")
        print("Veuillez indiquer un nom de feuille et de titre avant de valider.")
      }
      
    })
    
    observeEvent(input$enreg, {
      req(input$file1)
      req(input$feuille)
      req(input$title)
      
      # showModal(modalDialog("Enregistrement...", footer = NULL))
      # formatting
      if (input$source != "" & input$champ != "") {
        formater_auto(classeur = wb,
                      format = input$format,
                      liste_feuilles_avec_note = list_sheets_with_note,
                      liste_type_donnees = list_col_data_types)
        # save
        saveWorkbook(wb, file = paste("~", input$output_file, sep = "/"), overwrite = TRUE)
        # removeModal()
        shinyalert(title = "Enregistrement réussi", type = "success")
        print("Enregistrement réussi.")
        # } else if (input$.shinylogs_input[(length(input$.shinylogs_input) - 1)]$name != "validate") {
        #   shinyalert("Veuillez valider vos modifications avant d'enregistrer", type = "warning")
      } else {
        shinyalert("Veuillez indiquer une source et un champ avant d'enregistrer", type = "error")
      }
    })
  }
  
  shinyApp(ui = ui,
           server = server)
}

```

```{r examples-app_formatage, eval=FALSE}
library(agreste)
app_formatage()
```

```{r development-inflate, eval=FALSE}
fusen::inflate(flat_file = "dev/flat_appli_format.Rmd", vignette_name = "Application Shiny Formatage", check=F, overwrite = "yes")
```