# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  
  # expect_true(ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = "tab_iris") == 0)
  expect_error(ajouter_tableau_excel(classeur = nom_page, tableau = iris, nom_feuille = "tab_iris"),"Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur, tableau = "tab_iris", nom_feuille = "tab_iris"),"Le tableau doit \u00eatre un dataframe ou un tibble.")
  expect_error(ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = iris),"Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")

})

