# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("ajouter_champ fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  ajouter_tableau_excel(classeur = mon_classeur, 
                        nom_feuille = "iris",
                        tableau = iris)
  champ = "Un champ de blé"
  
  expect_error(ajouter_champ(classeur = champ,
                                    nom_feuille = "iris",
                                    champ = champ),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = iris),
               "Le champ doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = iris,
                                    champ = champ),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    format = "info rapide"),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    champ = champ,
                                    col_debut = 2,
                                    fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_champ(classeur = mon_classeur,
                             nom_feuille = "iris",
                             champ = champ,
                             col_debut = 2,
                             fusion = TRUE,
                             avec_titre = "non"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("Le champ est bien présent dans le workbook et identique à celui rentré en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  champ <- "Un champ de blé"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris",
                        ligne_debut = 5)
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Agreste",
                 format = "primeur",
                 avec_titre = FALSE)
  ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = champ,
                format = "primeur",
                avec_titre = FALSE)
  
  
  expect_equal(openxlsx::readWorkbook(mon_classeur,
                                      colNames = FALSE,
                                      skipEmptyRows = FALSE)$X1[dim(iris)[1]+5],
               paste("Champ :",
                     champ))
})

