# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")
  note = "Une note quelconque"
  
  expect_error(ajouter_note_lecture(classeur = nom_page, nom_feuille = "iris", note = note),"Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur, nom_feuille = "tab_iris", note = iris),"La note doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur, nom_feuille = iris, note = note),"Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur, nom_feuille = "iris", note = note, col_debut = "2"),"La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur, nom_feuille = "iris", note = note, col_debut = 2, style = "gras"),"Le style doit \u00eatre un objet de type Style.")

})

