# WARNING - Generated by {fusen} from /dev/flat_carte.Rmd: do not edit by hand

test_that("carte_rond_proportionnel works", {
  permis_construire_region_2020 <- agreste::permis_construire_region %>% 
  filter(annee_autorisation == 2020)

  ### création de la carte et sauvegarde du fichier carte
  carte_pc_2020 <-
    carte_rond_proportionnel(
      df = permis_construire_region_2020,
      colonne_code_zone_geo = REG,
      colonne_volume = PC,
      titre_carte = "Carte 1",
      sous_titre_carte = "Nombre de permis de construire délivré en 2020 par région",
      titre_legende_volume = "Nombre de permis de construire",
      save_carte = TRUE,
      path_carte = "carte.png"
    )
  
  expect_equal(class(carte_pc_2020), c("gg", "ggplot"))
  
  expect_error(
    carte_rond_proportionnel(
      df = permis_construire_region_2020,
      colonne_code_zone_geo = REG,
      colonne_volume = PC,
      titre_carte = "Carte 1",
      sous_titre_carte = "Nombre de permis de construire délivré en 2020 par région",
      titre_legende_volume = "Nombre de permis de construire",
      save_carte = TRUE,
      path_carte = "carte.png",
      zone_geographique = "BLABLA",
      niveau_representation = "region_metro"
    ),
    "La zone geographique doit etre dans la liste des choix possibles : france, ue, monde."
  )
  
  expect_error(
    carte_rond_proportionnel(
      df = permis_construire_region_2020,
      colonne_code_zone_geo = REG,
      colonne_volume = PC,
      titre_carte = "Carte 1",
      sous_titre_carte = "Nombre de permis de construire délivré en 2020 par région",
      titre_legende_volume = "Nombre de permis de construire",
      save_carte = TRUE,
      path_carte = "carte.png",
      niveau_representation = "BLABLA"
    ),
    "Le niveau de representation geographique doit etre dans la liste des choix possibles : pays, region_metro, departement_metro."
  )
  
})
