# WARNING - Generated by {fusen} from /dev/flat_carte.Rmd: do not edit by hand

test_that("donnees_fond_carte works", {
  
  #########################################
  ## test sur le message renvoyé en cas d'erreur de paramètres
  expect_error(
    donnees_fond_carte(
      zone_geographique = "BLABLA",
      niveau_representation = "region_metro"
    ),
    "La zone geographique doit etre dans la liste des choix possibles : france, ue, monde."
  )
  
  expect_error(
    donnees_fond_carte(
      zone_geographique = "france",
      niveau_representation = "BLABLA"
    ),
    "Le niveau de representation geographique doit etre dans la liste des choix possibles : pays, region_metro, departement_metro."
  )
  
  #########################################
  ### test sur France métro et région
  data_region_france <-
    donnees_fond_carte(zone_geographique = "france",
                       niveau_representation = "region_metro")
  ### nb region == 3
  expect_equal(nrow(data_region_france), 13)
  
  ### classes des colonnes du dataframe de sortie
  expect_equal(
    data_region_france %>% 
      purrr::map(class),
    list(
      NUTS_ID = "character",
      LEVL_CODE = "integer",
      CNTR_CODE = "character",
      NAME_LATN = "character",
      NUTS_NAME = "character",
      MOUNT_TYPE = "integer",
      URBN_TYPE = "integer",
      COAST_TYPE = "integer",
      FID = "character",
      geometry = c("sfc_MULTIPOLYGON", "sfc"),
      code_region = "character",
      code_dep = "character",
      centre = c("sfc_POINT", "sfc")
    )
  )
})

