# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that('Les styles dÃ©finis sont bien de type "Style"', {
  mes_styles <- creer_liste_style_excel()
  for (st in mes_styles) {
    expect_true(class(st) == "Style")
  }
})
