# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("Le formatage se fait correctement et sans erreur", {
  
  plan <- agreste::modele_plan
  
  temp_dir <- tempdir()
  
  file1 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file2 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file3 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file4 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file5 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file_plan <- tempfile(pattern = "file", tmpdir = temp_dir, fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  agreste::lait_vache %>%
    openxlsx::write.xlsx(file = paste(file4, "xlsx", sep = "."), rowNames = FALSE)
  agreste::scieries2020 %>%
    openxlsx::write.xlsx(file = paste(file5, "xlsx", sep = "."), rowNames = FALSE)
  
  plan$Nom_fichier[1] <- basename(file1)
  plan$Nom_fichier[2] <- basename(file2)
  plan$Nom_fichier[3] <- basename(file3)
  plan$Nom_fichier[4] <- basename(file4)
  plan$Nom_fichier[5] <- basename(file5)
  
  openxlsx::write.xlsx(plan, file_plan, rowNames = FALSE)
  
  expect_error(creer_excel_depuis_plan(plan = 1,
                                       datadir = temp_dir,
                                       format = "primeur",
                                       col_debut = 2,
                                       save = FALSE),
               "Le plan doit \u00eatre une cha\u00eene de caract\u00e8res ou un data frame.")
  expect_error(creer_excel_depuis_plan(plan = file_plan,
                                       datadir = temp_dir,
                                               format = "irapide",
                                               col_debut = 2,
                                               save = FALSE),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(creer_excel_depuis_plan(plan = file_plan,
                                       datadir = temp_dir,
                                               format = "chiffres_et_donnees",
                                               col_debut = "B",
                                               save = FALSE),
               "La colonne de d\u00e9but doit \u00eatre NULL ou bien un entier positif.")
  expect_error(creer_excel_depuis_plan(plan = file_plan,
                                       datadir = temp_dir,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = "oui"),
               "save doit \u00eatre TRUE ou FALSE")
  expect_error(creer_excel_depuis_plan(plan = file_plan,
                                       datadir = temp_dir,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = plan),
               "Le chemin du fichier \u00e0 sauvegarder doit \u00eatre une cha\u00eene de caract\u00e8res.")
  expect_error(creer_excel_depuis_plan(plan = file_plan,
                                       datadir = temp_dir,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = file_plan,
                                               type_virgule = ";"),
               'Le type de virgule doit \u00eatre "." ou ","')
})

test_that("Le classeur est bien modifié pour un c&d", {
  plan <- agreste::modele_plan
  
  temp_dir <- tempdir()
  
  file1 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file2 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file3 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file4 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file5 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file_plan <- tempfile(pattern = "file", tmpdir = temp_dir, fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  agreste::lait_vache %>%
    openxlsx::write.xlsx(file = paste(file4, "xlsx", sep = "."), rowNames = FALSE)
  agreste::scieries2020 %>%
    openxlsx::write.xlsx(file = paste(file5, "xlsx", sep = "."), rowNames = FALSE)
  
  plan$Nom_fichier[1] <- basename(file1)
  plan$Nom_fichier[2] <- basename(file2)
  plan$Nom_fichier[3] <- basename(file3)
  plan$Nom_fichier[4] <- basename(file4)
  plan$Nom_fichier[5] <- basename(file5)
  
  openxlsx::write.xlsx(plan, file_plan, rowNames = FALSE)
  
  workbook <- creer_excel_depuis_plan(plan = file_plan,
                                      datadir = temp_dir,
                                      format = "chiffres_et_donnees",
                                      col_debut = 1,
                                      save = FALSE,
                                      type_virgule = ".")
  expect_true(file.info(file_plan)$size > 0)
  expect_equal(length(names(workbook)),
               6)
  expect_equal(names(workbook),
               c(agreste::modele_plan$Nom_feuille, "Sommaire"))
  expect_equal(length(openxlsx::getStyles(workbook)),
               131)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[1])),
               23)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[2])),
               11)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[3])),
               17)
})

test_that("Le classeur est bien modifié pour un primeur", {
  plan <- agreste::modele_plan
  
  temp_dir <- tempdir()
  
  file1 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file2 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file3 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file4 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file5 <- tempfile(pattern = "file", tmpdir = temp_dir)
  file_plan <- tempfile(pattern = "file", tmpdir = temp_dir, fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  agreste::lait_vache %>%
    openxlsx::write.xlsx(file = paste(file4, "xlsx", sep = "."), rowNames = FALSE)
  agreste::scieries2020 %>%
    openxlsx::write.xlsx(file = paste(file5, "xlsx", sep = "."), rowNames = FALSE)
  
  plan$Nom_fichier[1] <- basename(file1)
  plan$Nom_fichier[2] <- basename(file2)
  plan$Nom_fichier[3] <- basename(file3)
  plan$Nom_fichier[4] <- basename(file4)
  plan$Nom_fichier[5] <- basename(file5)
  
  openxlsx::write.xlsx(plan, file_plan, rowNames = FALSE)
  
  workbook <- creer_excel_depuis_plan(plan = file_plan,
                                      datadir = temp_dir,
                                      format = "primeur",
                                      col_debut = 2,
                                      save = FALSE,
                                      path = file_plan,
                                      type_virgule = ".")

  expect_equal(length(names(workbook)),
               6)
  expect_equal(names(workbook),
               c(agreste::modele_plan$Nom_feuille, "Sommaire"))
  expect_equal(length(openxlsx::getStyles(workbook)),
               136)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[1])),
               24)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[2])),
               12)
  expect_equal(nrow(readWorkbook(workbook,
                                 skipEmptyRows = FALSE,
                                 colNames = FALSE,
                                 sheet = agreste::modele_plan$Nom_feuille[3])),
               18)
})

