# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("ajouter_note_lecture fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  openxlsx::addWorksheet(mon_classeur, "iris")
  note = "Une note quelconque"
  
  expect_error(ajouter_note_lecture(classeur = note,
                                    nom_feuille = "iris",
                                    note = note),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = iris),
               "La note doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = iris,
                                    note = note),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    format = "info rapide"),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 2,
                                    fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_note_lecture(classeur = mon_classeur,
                                    nom_feuille = "iris",
                                    note = note,
                                    col_debut = 2,
                                    avec_titre = "oui"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("La note est bien présente dans le workbook et identique à celle rentrée en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  note <- "Note de lecture"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris")
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "iris",
                       note = note,
                       format = "primeur",
                       avec_titre = FALSE)
  
  expect_equal(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[dim(iris)[1]+3], paste("Note de lecture :", note))
})

