# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("ajouter_source fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  ajouter_tableau_excel(classeur = mon_classeur, 
                        nom_feuille = "iris",
                        tableau = iris)
  source = "Une note quelconque"
  expect_error(ajouter_source(classeur = source,
                              nom_feuille = "iris",
                              source = source,
                              avec_note = FALSE),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = iris,
                              avec_note = FALSE),
               "La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = iris,
                              source = source,
                              avec_note = FALSE),
               "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              format = "info rapide",
                              avec_note = FALSE),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = "2",
                              avec_note = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 0,
                              avec_note = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = "oui",
                              avec_note = FALSE),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = TRUE,
                              avec_note = "non"),
               "Le param\u00e8tre avec_note doit \u00eatre TRUE ou FALSE.")
  expect_error(ajouter_source(classeur = mon_classeur,
                              nom_feuille = "iris",
                              source = source,
                              col_debut = 2,
                              fusion = TRUE,
                              avec_note = FALSE,
                              avec_titre = "non"),
               "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
})

test_that("La source est bien présente dans le workbook et identique à celle rentrée en paramètre", {
  mon_classeur <- openxlsx::createWorkbook()

  note <- "Une note de lecture"
  source <- "Une source quelconque"
  
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris,
                        nom_feuille = "iris",
                        col_debut = 5)
  ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "Données Iris",
                        format = "primeur")
  ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "iris",
                       note = note, 
                       format = "primeur",
                       avec_titre = FALSE)
  ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = source,
                 format = "primeur",
                 avec_note = TRUE,
                 avec_titre = FALSE)
  
  expect_equal(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[dim(iris)[1]+4], paste("Source :", source))
})

