# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                      tableau = iris,
                      nom_feuille = "iris",
                      col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "iris",
                        titre = "DonnÃ©es fleurs iris",
                        col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "iris",
                 source = "Ceci est une source quelconque",
                 col_debut = 2,
                 avec_note = FALSE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "iris",
                champ = "France mÃ©tropolitaine",
                col_debut = 2)

  agreste::ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = airquality,
                        nom_feuille = "airquality",
                        col_debut = 2)

  agreste::ajouter_titre_tableau(classeur = mon_classeur,
                        nom_feuille = "airquality",
                        titre = "DonnÃ©es qualitÃ© de l'air",
                        col_debut = 2)
  agreste::ajouter_note_lecture(classeur = mon_classeur,
                       nom_feuille = "airquality",
                       note = "blablabla",
                       col_debut = 2)
  agreste::ajouter_source(classeur = mon_classeur,
                 nom_feuille = "airquality",
                 source = "Eurostat",
                 col_debut = 2,
                 avec_note = TRUE)
  agreste::ajouter_champ(classeur = mon_classeur,
                nom_feuille = "airquality",
                champ = "Daily air quality measurements in New York, May to September 1973.",
                col_debut = 2)


  expect_error(formater_auto(classeur = "workbook",
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("iris"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"))),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = 2,
                             liste_feuilles_avec_note = c("iris"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"))),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c(1,2,3),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte"))),
               "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("iris"),
                             liste_type_donnees = c("decimal",
                                                    "decimal",
                                                    "decimal",
                                                    "decimal",
                                                    "texte")),
               "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  expect_error(formater_auto(classeur = mon_classeur,
                             format = "chiffres_et_donnees",
                             liste_feuilles_avec_note = c("iris"),
                             liste_type_donnees = list(c("decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "decimal",
                                                         "texte")),
                             col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")

})
