# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("ajouter_titre_primeur fonctionne correctement et renvoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")
  titre = "Données iris"
  
  expect_error(ajouter_titre_primeur(classeur = nom_page,
                                     titre = titre),
               "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = iris),
               "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = "2"),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = 0),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_titre_primeur(classeur = mon_classeur,
                                     titre = titre,
                                     col_debut = 2,
                                     fusion = "oui"),
               "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")

})

test_that("Le titre est le bon dans le workbook", {
  mon_classeur <- openxlsx::createWorkbook()
  titre = "Données iris"
  ajouter_tableau_excel(classeur = mon_classeur,
                        tableau = iris, 
                        nom_feuille = "iris",
                        col_debut = 5)
  ajouter_titre_primeur(classeur = mon_classeur,
                        titre = titre)
  expect_true(openxlsx::readWorkbook(mon_classeur, colNames = FALSE, skipEmptyRows = FALSE)$X1[1] == titre)
})

