# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")
  source = "Une source quelconque"
  
  expect_error(ajouter_source(classeur = nom_page, nom_feuille = "iris", source = source),"Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(ajouter_source(classeur = mon_classeur, nom_feuille = "tab_iris", source = iris),"La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur, nom_feuille = iris, source = source),"Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(ajouter_source(classeur = mon_classeur, nom_feuille = "iris", source = source, col_debut = "2"),"La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(ajouter_source(classeur = mon_classeur, nom_feuille = "iris", source = source, col_debut = 2, style = "gras"),"Le style doit \u00eatre un objet de type Style.")
  expect_error(ajouter_source(classeur = mon_classeur, nom_feuille = "iris", source = source, col_debut = 2, avec_note = 1), "La condition de note doit \u00eatre un bool\u00e9en, TRUE ou FALSE.")
})

