# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#library(xlsx)
test_that("Le formatage se fait correctement et sans erreur", {
  
  plan <- agreste::modele_plan
  
  file1 <- tempfile(pattern = "file", tmpdir = tempdir())
  file2 <- tempfile(pattern = "file", tmpdir = tempdir())
  file3 <- tempfile(pattern = "file", tmpdir = tempdir())
  file_plan <- tempfile(pattern = "file", tmpdir = tempdir(), fileext = ".xlsx")
  
  agreste::resultat_1 %>%
    write.csv(file = paste(file1, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_2 %>%
    write.csv(file = paste(file2, "csv", sep = "."), row.names = FALSE)
  agreste::resultat_3 %>%
    write.csv(file = paste(file3, "csv", sep = "."), row.names = FALSE)
  
  plan$Nom_fichier[1] <- file1
  plan$Nom_fichier[2] <- file2
  plan$Nom_fichier[3] <- file3
  
  write.xlsx(plan, file_plan, row.names = FALSE)
  
  expect_error(agreste::creer_excel_depuis_plan(plan = 1,
                                               format = "primeur",
                                               col_debut = 2,
                                               save = FALSE),
               "Le plan doit \u00eatre une cha\u00eene de caract\u00e8res ou un data frame.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "irapide",
                                               col_debut = 2,
                                               save = FALSE),
               'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = "B",
                                               save = FALSE),
               "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = "oui"),
               "save doit \u00eatre TRUE ou FALSE")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = plan),
               "Le chemin du fichier \u00e0 sauvegarder doit \u00eatre une cha\u00eene de caract\u00e8res.")
  expect_error(agreste::creer_excel_depuis_plan(plan = file_plan,
                                               format = "chiffres_et_donnees",
                                               col_debut = 2,
                                               save = TRUE,
                                               path = file_plan,
                                               type_virgule = ";"),
               'Le type de virgule doit \u00eatre "." ou ","')
})

