# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

test_that("mon_classeur fonctionne correctement and envoie une erreur quand il le faut", {
  mon_classeur <- openxlsx::createWorkbook()
  nom_page <- "nom_onglet"
  openxlsx::addWorksheet(mon_classeur, "iris")

  expect_error(geler(classeur = nom_page, nom_feuille = "iris"),"Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = iris),"Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = "iris", ligne = "1"),"La ligne \u00e0 geler doit \u00eatre un entier positif.")
  expect_error(geler(classeur = mon_classeur, nom_feuille = "iris", ligne = 1, col = "2"),"La colonne \u00e0 geler doit \u00eatre un entier positif.")
})
