# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Ajouter la source sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter une source sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param source la source à ajouter
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param avec_note si une note de lecture est présente ou pas, par défaut TRUE
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
#' 
#' # Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
#' # Ajout de la source
#' # Sauvegarde du classeur
#' # Ouverture du classeur
#' library(openxlsx)
#' library(agreste)
#' mon_classeur <- createWorkbook()
#' 
#' mes_styles <- creer_liste_style_excel()
#' 
#' start_ligne = 3
#' start_col = 2
#' nb_col = ncol(iris)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = iris,
#'                       nom_feuille = "iris")
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$ligne_titre,
#'          rows = start_ligne,
#'          cols = start_col:(nb_col+start_col-1))
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 2)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 3)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 4)
#' addStyle(wb = mon_classeur, 
#'         sheet = "iris",
#'         style = mes_styles$decimal_italique,
#'         rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'         cols = 5)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$texte,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 6)
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "iris",
#'                       titre = "Iris",
#'                       col_debut = start_col,
#'                       format = "chiffres_et_donnees")
#' 
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "iris",
#'                source = "Ceci est une source quelconque",
#'                format = "chiffres_et_donnees",
#'                col_debut = start_col,
#'                avec_note = FALSE)
#' 
#' start_ligne = 3
#' start_col = 2
#' nb_col = ncol(airquality)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = airquality,
#'                       nom_feuille = "airquality")
#' 
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$ligne_titre,
#'          rows = start_ligne,
#'          cols = start_col:(nb_col+start_col-1))
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$numerique,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 2)
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$numerique,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 3)
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 4)
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$numerique,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 5)
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$numerique,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 6)
#' addStyle(wb = mon_classeur,
#'          sheet = "airquality",
#'          style = mes_styles$numerique,
#'          rows = (start_ligne+1):(nrow(airquality)+start_ligne),
#'          cols = 7)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "airquality",
#'                       titre = "Données qualité de l'air",
#'                       col_debut = 2)
#' 
#' ajouter_note_lecture(classeur = mon_classeur,
#'                      nom_feuille = "airquality",
#'                      note = "blablabla",
#'                      col_debut = start_col)
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "airquality",
#'                source = "Eurostat",
#'                col_debut = start_col,
#'                avec_note = TRUE)
#' 
#' saveWorkbook(wb = mon_classeur,
#'              file = "tableau.xlsx",
#'              overwrite = TRUE)
#' 
#' browseURL("tableau.xlsx")
#' 
ajouter_source <- function(classeur,
                           nom_feuille,
                           source,
                           format = "chiffres_et_donnees",
                           col_debut = 2,
                           avec_note = TRUE,
                           fusion = TRUE,
                           avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(source),
              msg = "La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_note) == "logical",
              msg = "Le param\u00e8tre avec_note doit \u00eatre TRUE ou FALSE.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style = creer_liste_style_excel(format = format)
  style_source <- style$source
  last_row = nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  if (isTRUE(avec_note)) {
    ligne_de_depart_source = 0
  } else {
    ligne_de_depart_source = 1
  }
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_source <- last_row + ligne_de_depart_source + 1 + nb_row_to_add

  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_source)
  }
  writeData(classeur, nom_feuille, paste("Source :",source), startCol = col_debut, startRow = row_source)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_source, rows = row_source, cols = col_debut)
}
