# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Ajouter le titre du primeur dans la première cellule de chaque feuille
#'
#' Cette fonction permet d'ajouter le titre en haut de chaque feuille 
#' d'un classeur de type primeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param titre le titre à ajouter
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
#' library(openxlsx)
#' library(agreste)
#' mon_classeur <- createWorkbook()
#' 
#' mes_styles <- creer_liste_style_excel(format = "primeur")
#' 
#' start_ligne = 5
#' start_col = 2
#' nb_col = ncol(iris)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = iris,
#'                       nom_feuille = "iris",
#'                       ligne_debut = 5)
#' 
#' ## Formatage
#' 
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$ligne_titre,
#'          rows = start_ligne,
#'          cols = start_col:(nb_col+start_col-1))
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 2)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 3)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 4)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$decimal_italique,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 5)
#' addStyle(wb = mon_classeur,
#'          sheet = "iris",
#'          style = mes_styles$texte,
#'          rows = (start_ligne+1):(nrow(iris)+start_ligne),
#'          cols = 6)
#' 
#' ## Ajout du titre 
#' 
#' ajouter_titre_primeur(classeur = mon_classeur,
#'                       titre = "Iris")
#' 
#' ## Sauvegarde
#' saveWorkbook(wb = mon_classeur,
#'              file = "tableau.xlsx",
#'              overwrite = TRUE)
#' 
#' browseURL("tableau.xlsx")
ajouter_titre_primeur <- function(classeur,
                                  titre,
                                  col_debut = 2,
                                  fusion = TRUE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(titre),
              msg = "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  
  liste_style = creer_liste_style_excel(format = "primeur")
  style_titre_primeur = liste_style$titre_primeur
  
  write_row <- 1 
  
  for (feuille in names(classeur)) {
    if (isTRUE(fusion)) {
      nb_col = ncol(readWorkbook(classeur, sheet = feuille))
      if (!is.null(nb_col)) {
        mergeCells(classeur, feuille, cols = col_debut:(col_debut+nb_col-1), rows = write_row)
      }
    }
    writeData(classeur, feuille, titre, startCol = col_debut, startRow = write_row)
    addStyle(wb = classeur, sheet = feuille, style = style_titre_primeur, rows = write_row, cols = col_debut)
  }
  
  
}
