# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Ajouter un tableau dans une feuille excel
#'
#' Cette fonction crée une nouvelle feuille dans le classeur passé en paramètre et y insère un tableau mis en forme.
#'
#' @param classeur workbook créé avec openXLSX
#' @param tableau dataframe ou tibble à insérer dans une nouvelle feuille
#' @param nom_feuille nom de la nouvelle feuille
#' @param ligne_debut la ligne à laquelle démarre le tableau
#' @param col_debut la colonne à laquelle démarre le tableau
#' 
#' @return Rien n'est renvoyé mais l'objet classeur a une nouvelle feuille
#' 
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx writeData
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
#' 
#' # Création d'un classeur avec une feuille contenant iris et une feuille contenant airquality
#' # Sauvegarde du classeur
#' # Ouverture du classeur
#' library(openxlsx)
#' library(agreste)
#' mon_classeur <- createWorkbook()
#' 
#' mes_styles <- creer_liste_style_excel()
#' 
#' start_ligne = 3
#' start_col = 2
#' nb_col = ncol(iris)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = "iris")
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$ligne_titre, rows = start_ligne, cols = start_col:(nb_col+start_col-1))
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 2)
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 3)
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 4)
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$decimal_italique, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 5)
#' addStyle(wb = mon_classeur, sheet = "iris", style = mes_styles$texte, rows = (start_ligne+1):(nrow(iris)+start_ligne), cols = 6)
#' 
#' start_ligne = 3
#' start_col = 2
#' nb_col = ncol(airquality)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur, tableau = airquality, nom_feuille = "airquality")
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$ligne_titre, rows = start_ligne, cols = start_col:(nb_col+start_col-1))
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 2)
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 3)
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$decimal, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 4)
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 5)
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 6)
#' addStyle(wb = mon_classeur, sheet = "airquality", style = mes_styles$numerique, rows = (start_ligne+1):(nrow(airquality)+start_ligne), cols = 7)
#' 
#' saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
#' 
#' browseURL("tableau.xlsx")
#' 
ajouter_tableau_excel <- function(classeur, tableau, nom_feuille, ligne_debut = 3, col_debut = 2) {

  assert_that(class(classeur)=="Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.data.frame(tableau),
              msg = "Le tableau doit \u00eatre un dataframe ou un tibble.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(ligne_debut > 0,
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(ligne_debut),
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  addWorksheet(wb = classeur,
               sheetName = nom_feuille)
  writeData(wb = classeur,
            sheet = nom_feuille,
            x = tableau,
            startCol = col_debut,
            startRow = ligne_debut)
}
