# WARNING - Generated by {fusen} from /dev/flat_appli_format.Rmd: do not edit by hand

#' Ouvrir l'application Shiny d'édition du tableur
#' 
#' Cette fonction permet d'ouvrir l'interface graphique s'appuyant 
#' sur les fonctions de formatage du package pour éditer des tableaux plus rapidement
#' 
#' @return Rien n'est renvoyé, l'appli s'ouvre.
#' 
#' @importFrom shiny runApp
#' @importFrom shiny shinyAppDir
#' @importFrom shiny fileInput
#' @importFrom shiny tags
#' @importFrom shiny checkboxInput
#' @importFrom shiny radioButtons
#' @importFrom shiny textInput
#' @importFrom shiny tableOutput
#' @importFrom shiny uiOutput
#' @importFrom shiny actionButton
#' @importFrom shiny req
#' @importFrom shiny renderUI
#' @importFrom shiny selectInput
#' @importFrom shiny observeEvent
#' @importFrom shiny showModal
#' @importFrom shiny removeModal
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyalert shinyalert
#' @importFrom shinyWidgets prettyRadioButtons
#' @importFrom bs4Dash dashboardPage
#' @importFrom bs4Dash dashboardHeader
#' @importFrom bs4Dash dashboardSidebar
#' @importFrom bs4Dash dashboardFooter
#' @importFrom bs4Dash dashboardBody
#' @importFrom magrittr %>%
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx saveWorkbook
#' 
#' @export
#' 
#' @examples
#' library(agreste)
#' app_formatage()
app_formatage <- function() {
  Rdir <- getSrcDirectory(function(x) {x})
  script_dir <- substring(Rdir, first = 1, last = nchar(Rdir) - 2)
  runApp(shinyAppDir(paste(script_dir, "app/tables/app", sep = "/")))
}
