# WARNING - Generated by {fusen} from /dev/flat_appli_format.Rmd: do not edit by hand

#' Ouvrir l'application Shiny d'édition du tableur
#' 
#' Cette fonction permet d'ouvrir l'interface graphique s'appuyant 
#' sur les fonctions de formatage du package pour éditer des tableaux plus rapidement
#' 
#' @return Rien n'est renvoyé, l'appli s'ouvre.
#' 
#' @importFrom shiny runApp
#' @importFrom shiny shinyAppDir
#' @importFrom shiny fileInput
#' @importFrom shiny shinyApp
#' @importFrom shiny tags
#' @importFrom shiny checkboxInput
#' @importFrom shiny radioButtons
#' @importFrom shiny textInput
#' @importFrom shiny tableOutput
#' @importFrom shiny uiOutput
#' @importFrom shiny actionButton
#' @importFrom shiny req
#' @importFrom shiny renderUI
#' @importFrom shiny selectInput
#' @importFrom shiny observeEvent
#' @importFrom shiny showModal
#' @importFrom shiny removeModal
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyalert shinyalert
#' @importFrom shinyWidgets prettyRadioButtons
#' @importFrom bs4Dash dashboardPage
#' @importFrom bs4Dash dashboardHeader
#' @importFrom bs4Dash dashboardSidebar
#' @importFrom bs4Dash dashboardFooter
#' @importFrom bs4Dash dashboardBody
#' @importFrom magrittr %>%
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx saveWorkbook
#' @importFrom openxlsx removeCellMerge
#' @importFrom openxlsx removeWorksheet
#' @importFrom purrr map
#' @importFrom purrr set_names
#' @importFrom purrr %>%
#' @importFrom stringr str_replace
#' 
#' @export
#' 
#' @examples
#' 
#' library(agreste)
#' \dontrun{
#' app_formatage()
#' }
app_formatage <- function() {
  
  wb <- createWorkbook()
  list_sheets_with_note <- c(" ")
  list_col_data_types <- list()
  index_current_sheet <- 0
  
  plan <- modele_plan[NULL,]
  
  wd <- getwd()
  
  ui = dashboardPage(
  skin = "light",
  title = "Mise en forme de tableaux",
  
  header = dashboardHeader(title = "Mise en forme de tableaux"),
  
  sidebar = dashboardSidebar(
    skin = "light",
    
    fileInput(
      inputId = "upload",
      label = "Choisir les fichiers",
      multiple = TRUE,
      accept = c("text/csv",
                 "text/comma-separated-values,text/plain",
                 ".csv",
                 ".xlsx",
                 ".rds",
                 ".Rds",
                 ".parquet",
                 ".xls")),
    
    # Horizontal line ----
    tags$hr(),
    
    # Input: Checkbox if file has header ----
    checkboxInput("header", "Header", TRUE),
    
    # Input: Select separator ----
    radioButtons("sep", "Separateur",
                 choices = c(Virgule = ",",
                             "Point Virgule" = ";",
                             Tab = "\t"),
                 selected = ","),
    
    radioButtons("virg", "Séparateur décimal",
                 choices = c(Virgule = ",",
                             Point = "."),
                 selected = ","),
  ),
  # controlbar = dashboardControlbar(),
  footer = dashboardFooter(),
  body = dashboardBody(
    DTOutput("files"),
    DTOutput("contents") %>% withSpinner(),
    prettyRadioButtons(inputId = "format",
                       label = "Format",
                       choices = c("Chiffres et données" = "chiffres_et_donnees",
                                   Primeur = "primeur"),
                       selected = "chiffres_et_donnees"),
    textInput("feuille", "Nom de la feuille :"),
    textInput("title", "Titre du tableau :"),
    # Output: Data file ----
    
    uiOutput("deroul"),
    uiOutput("larg"),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_header", "Lignes de surtitre")),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_sous_titre", "Lignes de sous-titre")),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_section", "Lignes de section")),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_precision", "Lignes de précision")),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_sous_total", "Lignes de sous-total")),
    div(style="display: inline-block;vertical-align:top; width: 100px;",
        actionButton("lignes_total", "Lignes de total")),
    tags$hr(),
    div(style="display: inline-block;vertical-align:top; width: 300px;",
        textInput("note", "Note de lecture :")),
    div(style="display: inline-block;vertical-align:top; width: 300px;",
        textInput("source", "Source")),
    div(style="display: inline-block;vertical-align:top; width: 300px;",
        textInput("champ", "Champ")),
    
    tags$hr(),
    actionButton("validate", "Valider"),
    textInput("output_file", "Nom du fichier de sortie", value = "output.xlsx"),
    actionButton("exporter", "Exporter le plan"),
    actionButton("enreg", "Enregistrer le fichier Excel")
  ),
  )
  
  server = function(input, output) {
    
    # track_usage(
    #   storage_mode = store_null(console = FALSE),
    #   what = "input"
    # )
    
    options(shiny.maxRequestSize=15*1024^2) # set maximum file size to 15MB
    
    observeEvent(input$upload, {
      plan <<- modele_plan[NULL,]
    })
    
    output$files <- renderDataTable({
      req(input$upload)
      datatable(input$upload, selection = list(mode = "single", selected = 1))
    })
    
    all_files <- reactive({
      req(input$upload)
      map(input$upload$datapath, read_any_file) %>%
        set_names(input$upload$name)
      
    })
    
    output$contents <- renderDataTable({
      
      req(input$upload)
      req(all_files())

      all_files()[[
        input$upload$name[[input$files_rows_selected]]
      ]]
      
    })
    
    output$deroul <- renderUI({
      req(input$upload)
      req(all_files())
      
      # df <- read_any_file(input$upload$datapath,
      #                     header = input$header,
      #                     sep = input$sep,
      #                     decimal_mark = input$virg)
      
      df <- all_files()[[
        input$upload$name[[input$files_rows_selected]]
      ]]
      
      lapply(1:ncol(df), function(i) {
        div(style="display: inline-block;vertical-align:top; width: 100px;",
            selectInput(inputId = paste("col_",
                                        as.character(i),
                                        sep = ""),
                        label = paste("Colonne",
                                      as.character(i),
                                      sep = " "),
                        choices = c("Texte" = "texte",
                                    "Entier" = "numerique",
                                    "Décimal" = "decimal")))
        })
      })
      
    output$larg <- renderUI({
      req(input$upload)
      req(all_files())
    
      # df <- read_any_file(input$upload$datapath,
      #                   header = input$header,
      #                   sep = input$sep,
      #                   decimal_mark = input$virg)
      
      df <- all_files()[[
      input$upload$name[[input$files_rows_selected]]
      ]]
      
      lapply(1:ncol(df), function(i) {
        div(style="display: inline-block;vertical-align:top; width: 100px;",
            numericInput(inputId = paste("taille_",
                                        as.character(i),
                                        sep = ""),
                      label = paste("Largeur",
                                      as.character(i),
                                      sep = " "),
                      value = 83/ncol(df),
                      min = 3,
                      max = 83,
                      step = 0.01))
      })
    })
    
    observeEvent(input$contents$name, {
      updateTextInput(inputId = "feuille", value = plan$Nom_feuille[input$files_row_selected])
      print(plan)
    })
      
    observeEvent(input$validate, {
      req(input$upload)
      req(all_files())
      
      df <- all_files()[[
        input$upload$name[[input$files_rows_selected]]
      ]]
      
      plan <<- valider_donnees(plan = plan, input = input, df = df)
      shinyalert("Bouton en cours de développement", type = "info")
      
    })
    
    observeEvent(input$enreg, {
      req(input$upload)
      req(all_files())
      shinyalert("Bouton en cours de développement", type = "info")
      
      
    })
  }
  
  shinyApp(ui = ui,
           server = server)
}


#' Enregistre les données de l'app vers le plan
#' 
#' @param plan le dataframe de plan
#' @param input les inputs shiny
#' @param df le tableau actuellement sélectionné
#' 
#' @return le dataframe de plan modifié
#' @noRd
valider_donnees <- function(plan, input, df) {
  
  index_tab <- input$files_rows_selected
  filename <- input$upload$name[index_tab]
  file_ext <- get.ext(filename)
  n_tab <- length(input$upload$name)
  if (dim(plan)[1] == 0) {
    lignes <- data.frame(matrix("", n_tab, ncol(plan)))
    names(lignes) <- names(plan)
    plan <- rbind(plan, lignes)
  }
  
  
  
  vec_data_types <- c()
  vec_col_width <- c()
  
  for (i in 1:ncol(df)) {
    id_types <- eval(parse(text = paste("input$col_", as.character(i), sep = "")))
    id_widths <- eval(parse(text = paste("input$taille_", as.character(i), sep = "")))
    vec_data_types <- append(vec_data_types, id_types)
    vec_col_width <- append(vec_col_width, id_widths)
  }
  plan$Nom_fichier[index_tab] <- str_replace(filename,
                                             paste(".", file_ext, sep = ""),
                                             "")
  plan$Type[index_tab] <- file_ext
  plan$Nom_feuille[index_tab] <- input$feuille
  
  return(plan)
} 
