# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Applique une taille de colonne automatiquement sur un workbook
#'
#' Cette fonction permet d'appliquer une taille de colonne automatiquement,
#' le total étant égal à 89, et les colonnes de texte étant plus grandes
#' que les autres
#'
#' @param classeur Le classeur excel, objet de type workbook
#' @param save LGL TRUE si export du classeur au format xlsx
#' @param path CHAR chemin vers le tableau à sauvegarder
#'
#' @return un objet de type workbook formaté
#' 
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' @importFrom openxlsx read.xlsx
#' @importFrom openxlsx saveWorkbook
#' @importFrom openxlsx write.xlsx
#' 
#' @export
#'
#' @examples
