# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Crée un classeur et le formate
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi, simplement à partir d'un plan. Les fichiers indiqués dans le plan doivent être dans le répertoire de travail.
#'
#' @param plan fichier .xlsx ou data frame contenant les détails pour chaque tableau 
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur"
#' @param type_virgule CHAR le type de séparation décimale utilisée : "." ou ","
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param save LGL TRUE si export du classeur au format xlsx
#' @param path CHAR chemin vers le tableau à sauvegarder
#'
#' @return un objet de type workbook formaté
#' 
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' @importFrom openxlsx read.xlsx
#' @importFrom openxlsx createWorkbook
#' @importFrom openxlsx saveWorkbook
#' @importFrom openxlsx write.xlsx
#' @importFrom stringr str_trim
#' 
#' @export
#'
#' @examples
#' library(agreste)
#' library(dplyr)
#' library(openxlsx)
#' ### Import du fichier de plan
#' plan = agreste::modele_plan
#' 
#' ### Création des csv 
#' agreste::resultat_1 %>%
#'   write.csv(file = "resultat_1.csv", row.names = FALSE)
#' agreste::resultat_2 %>%
#'   write.csv(file = "resultat_2.csv", row.names = FALSE)
#' agreste::resultat_3 %>%
#'   write.csv(file = "resultat_3.csv", row.names = FALSE)
#' write.xlsx(plan, "plan.xlsx", row.names = FALSE)
#' ### Formatage
#' workbook <- creer_excel_depuis_plan(plan = "plan.xlsx",
#'                                     format = "primeur",
#'                                     col_debut = 2,
#'                                     save = TRUE,
#'                                     path = "document_a_envoyer.xlsx")
#' browseURL("document_a_envoyer.xlsx")
#' 
creer_excel_depuis_plan <- function(plan,
                                    format,
                                    type_virgule = ",",
                                    col_debut,
                                    save = TRUE,
                                    path = "tableau1.xlsx") {
  
  assert_that(class(plan) %in% c("character", "data.frame"),
              msg = "Le plan doit \u00eatre une cha\u00eene de caract\u00e8res ou un data frame.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(type_virgule %in% c(",", "."),
              msg = 'Le type de virgule doit \u00eatre "." ou ","')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(save) == "logical",
              msg = "save doit \u00eatre TRUE ou FALSE")
  assert_that(class(path) == "character",
              msg = "Le chemin du fichier \u00e0 sauvegarder doit \u00eatre une cha\u00eene de caract\u00e8res.")
  
  if (class(plan) == "character") {
    plan = read.xlsx(plan,
                     colNames = TRUE,
                     rowNames = FALSE)
  }
  i <- 0
  for (liste in plan$Type_colonnes) {
    i <- i + 1
    test_list <- strsplit(liste,
                     split = ", ")[[1]]
    for (type in test_list) {
      assert_that(type %in% c("decimal", "texte", "numerique"),
                  msg = paste("Problème dans la colonne Type_colonnes, tableau ", i, ". Veuillez la vérifier.", sep = ""))
    }
  }
  
  plan[,12:18][is.na(plan[,12:18])] <- 0
  
  nb_tab = nrow(plan)
  
  ligne_debut <- 3 + row_to_add_format(format = format)
  
  liste_feuilles_note <- c()
  liste_data_types <- list()
  liste_lignes_titre <- c()
  liste_lignes_section <- list()
  liste_lignes_sous_total <- list()
  liste_lignes_precision <- list()
  liste_lignes_total <- list()
  liste_col_widths <- list()
  
  
  titre_doc = plan$Titre_document[1]
  
  wb = createWorkbook()
  
  for (tab in 1:nb_tab) {
    filename <- paste(plan$Nom_fichier[tab],
                      plan$Type[tab],
                      sep = ".")
    data <- read.csv(filename,
                     header = TRUE,
                     check.names = FALSE,
                     dec = type_virgule)
    feuille <- plan$Nom_feuille[tab]
    titre <- plan$Titre[tab]
    if (str_trim(plan$Note_de_lecture[tab]) == "" | is.na(plan$Note_de_lecture[tab])) {
      avec_note <- FALSE
    } else {
      avec_note <- TRUE
    }
    source <- plan$Source[tab]
    champ <- plan$Champ[tab]
    if (str_trim(plan$Taille_colonnes[tab]) == "auto") {
      liste_col_widths <- append(liste_col_widths, "auto")
    } else {
      liste_col_widths <- append(liste_col_widths,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Taille_colonnes[tab]), split = ", ")))))
    }
    liste_data_types <- append(liste_data_types,
                               strsplit(plan$Type_colonnes[tab],
                                        split = ", "))
    liste_lignes_titre <- append(liste_lignes_titre,
                                 as.numeric(unlist(strsplit(str_trim(plan$Lignes_titre[tab]), split = ", "))))
    liste_lignes_section <- append(liste_lignes_section,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_section[tab]), split = ", ")))))
    liste_lignes_sous_total <- append(liste_lignes_sous_total,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_sous_total[tab]), split = ", ")))))
    liste_lignes_precision <- append(liste_lignes_precision,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_precision[tab]), split = ", ")))))
    liste_lignes_total <- append(liste_lignes_total,
                                 list(as.numeric(unlist(strsplit(str_trim(plan$Lignes_total[tab]), split = ", ")))))
    
    agreste::ajouter_tableau_excel(classeur = wb,
                                   tableau = data,
                                   nom_feuille = feuille,
                                   ligne_debut = ligne_debut,
                                   col_debut = col_debut)
    
    agreste::ajouter_titre_tableau(classeur = wb,
                                   nom_feuille = feuille,
                                   titre = titre,
                                   col_debut = col_debut,
                                   format = format)
    if (isTRUE(avec_note)) {
      liste_feuilles_note <- append(liste_feuilles_note, feuille)
      agreste::ajouter_note_lecture(classeur = wb,
                                    nom_feuille = feuille,
                                    note = plan$Note_de_lecture[tab],
                                    col_debut = col_debut,
                                    format = format)
    } 
    
    agreste::ajouter_source(classeur = wb,
                              nom_feuille = feuille,
                              source = source,
                              col_debut = col_debut,
                              avec_note = avec_note,
                              format = format)
    agreste::ajouter_champ(classeur = wb,
                           nom_feuille = feuille,
                           champ = champ,
                           col_debut = col_debut,
                           format = format)
  }
  if (format == "primeur") {
      agreste::ajouter_titre_primeur(classeur = wb,
                                     titre = titre_doc,
                                     col_debut = col_debut,
                                     fusion = TRUE)
  }
  agreste::taille_colonnes(classeur = wb,
                          liste_type_donnees = liste_data_types,
                          largeurs = liste_col_widths,
                          col_debut = col_debut)
  agreste::formater_auto(wb,
                         format = format,
                         liste_feuilles_avec_note = liste_feuilles_note,
                         liste_type_donnees = liste_data_types,
                         liste_lignes_titre = liste_lignes_titre,
                         liste_lignes_section = liste_lignes_section,
                         liste_lignes_sous_total = liste_lignes_sous_total,
                         liste_lignes_precision = liste_lignes_precision,
                         liste_lignes_total = liste_lignes_total,
                         col_debut = col_debut,
                         avec_titre = TRUE)
  if (isTRUE(save)) {
    saveWorkbook(wb, file = path, overwrite = TRUE)
  }
  
  return(wb)
}


