# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand


#' Parametrer le tableur excel
#' 
#' Cette fonction permet de créer une liste avec tous les styles utiles aux publications Agreste xlsx
#' @param format le format choisi : "chiffres_et_donnees" ou "primeur"
#'
#' @return une liste avec tous les styles disponibles (objets openxls)
#' @export
#' 
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#'
#' @examples
#' library(agreste)
#' mes_styles <- creer_liste_style_excel(format = "chiffres_et_donnees")
#' 
#' #exemples
#' mes_styles$ligne_titre
#' mes_styles$numerique
#' 
creer_liste_style_excel <- function(format = "chiffres_et_donnees") {
  assert_that((format %in% c("chiffres_et_donnees", "primeur")), msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  
  options("openxlsx.borderStyle" = "thin")
  options("openxlsx.borderColour" = "black")
  options("openxlsx.dateFormat" = "mm/dd/yyyy")
  options("openxlsx.paperSize" = 9)
  options("openxlsx.orientation" = "portrait")
  
  if (format == "chiffres_et_donnees") {
    font <- "Marianne"
  } else if (format == "primeur") {
    font <- "Calibri"
  }
  
  titleStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <- list(titre = titleStyle)
  
  titre_primeur_style <- createStyle(
    fontName = font,
    fontSize = 14,
    fontColour = "#548235",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(titre_primeur = titre_primeur_style))
  
  subtitleStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    textDecoration = "italic",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sous_titre = subtitleStyle))
  
  headerStyle <- switch(
    format,
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      fgFill = "#FF8D7E",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "white",
      halign = "center",
      valign = "center",
      fgFill = "#548235",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(ligne_titre = headerStyle))

  
  unitsUnifStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    textDecoration = "italic",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(lignes_unite_uniforme = unitsUnifStyle))
  
  unitsDiffStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    textDecoration = "italic",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(lignes_unites_differentes = unitsDiffStyle))
  
  dataStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(texte = dataStyleText))
  
  
  dataStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style, values = c(numerique = dataStyleNum))
  
  dataStyleNumDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.00"
  )
  
  liste_style <-
    append(liste_style, values = c(decimal = dataStyleNumDecimal))
  
  
  dataItalicStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(texte_italique = dataItalicStyleText))
  
  
  dataItalicStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_italique = dataItalicStyleNum))
  
  
  dataItalicStyleNumUneDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.00"
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_italique = dataItalicStyleNumUneDecimal))
  
  
  dataTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(texte_total = dataTotalStyleText))
  
  
  dataTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(numerique_total = dataTotalStyleNum))
  
  
  dataTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_total = dataTotalStyleNumDecimal))
  
  
  dataSubTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(texte_sous_total = dataSubTotalStyleText))
  
  
  
  dataSubTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_sous_total = dataSubTotalStyleNum))
  
  
  dataSubTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_sous_total = dataSubTotalStyleNumDecimal))
  
  
  dataPrecisionStyleText1 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 1,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_1 = dataPrecisionStyleText1))
  
  dataPrecisionStyleText2 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 2,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_2 = dataPrecisionStyleText2))
    
  dataPrecisionStyleText3 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 3,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_3 = dataPrecisionStyleText3))
  
  dataPrecisionStyleText4 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 4,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_4 = dataPrecisionStyleText4))
  
  dataSectionStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      fgFill = "#c6ddb4",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(texte_section = dataSectionStyleText))
  
  
  noteStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    borderColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <- append(liste_style, values = c(note = noteStyle))
  
  sourceStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(source = sourceStyle))
  
  
  champStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(champ = champStyle))
  
  sommaireSectionStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "left",
    valign = "center",
    fgFill = "#FF8D7E",
    borderColour = "black",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style,
           values = c(sommaire_section = sommaireSectionStyle))
  
  
  sommaireSection2Style <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    indent = 1,
    halign = "left",
    valign = "center",
    fgFill = "#FFE2DB",
    borderColour = "black",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style,
           values = c(sommaire_section2 = sommaireSection2Style))
  
  
  sommaireSheetStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    indent = 3,
    halign = "left",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sommaire_lien = sommaireSheetStyle))
  
  retourSommaireSheetStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "center",
    valign = "center",
    fgFill = "#FF8D7E",
    wrapText = TRUE
  )
  liste_style <-
    append(liste_style,
           values = c(bouton_retour_sommaire = retourSommaireSheetStyle))
  
  return(liste_style)
  
}


#' Renvoie le nombre de lignes à ajouter selon le format
#' 
#' @param format CHAR le format choisi entre "chiffres_et_donnees" et "primeur"
#' 
#' @return NUM le nombre de lignes à ajouter
#' @noRd
row_to_add_format <- function(format) {
  if (format == "chiffres_et_donnees") {
    return(0)
  } else {
    return(2)
  }
}
