# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Ajouter le champ sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter un champ sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param champ le champ à ajouter
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_champ <- function(classeur,
                          nom_feuille,
                          champ,
                          format = "chiffres_et_donnees",
                          col_debut = 2,
                          fusion = TRUE,
                          avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(champ),
              msg = "Le champ doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style <- creer_liste_style_excel(format = format)
  style_champ <- style$champ
  last_row <- nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_champ <- last_row + 1 + nb_row_to_add

  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_champ)
  }
  writeData(classeur, nom_feuille, paste("Champ :",champ), startCol = col_debut, startRow = row_champ)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_champ, rows = row_champ, cols = col_debut)
}

#' Ajouter une note de lecture sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter une note de lecture sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param note la note à écrire
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom openxlsx setRowHeights
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_note_lecture <- function(classeur,
                                 nom_feuille,
                                 note,
                                 format = "chiffres_et_donnees",
                                 col_debut = 2,
                                 fusion = TRUE,
                                 avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(note),
              msg = "La note doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style <- creer_liste_style_excel(format = format)
  style_note <- style$note
  last_row <- nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_note <- last_row + 2 + nb_row_to_add
    
  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_note)
  }
  writeData(classeur, nom_feuille, paste("Note de lecture :", note), startCol = col_debut, startRow = row_note)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_note, rows = row_note, cols = col_debut)
  setRowHeights(wb = classeur,
                sheet = nom_feuille,
                rows = row_note,
                heights = (1 + nchar(paste("Note de lecture :", note))%/%100)*15)
}

#' Ajouter la source sous un tableau dans une feuille d'un fichier xlsx
#'
#' Cette fonction permet d'ajouter une source sous un tableau dans une feuille Excel
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param source la source à ajouter
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param avec_note si une note de lecture est présente ou pas, par défaut TRUE
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_source <- function(classeur,
                           nom_feuille,
                           source,
                           format = "chiffres_et_donnees",
                           col_debut = 2,
                           avec_note = TRUE,
                           fusion = TRUE,
                           avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(source),
              msg = "La source doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(class(format) == "character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_note) == "logical",
              msg = "Le param\u00e8tre avec_note doit \u00eatre TRUE ou FALSE.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  style = creer_liste_style_excel(format = format)
  style_source <- style$source
  last_row = nrow(readWorkbook(classeur, sheet = nom_feuille, skipEmptyRows = FALSE, colNames = FALSE))
  if (isTRUE(avec_note)) {
    ligne_de_depart_source = 0
  } else {
    ligne_de_depart_source = 1
  }
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  row_source <- last_row + ligne_de_depart_source + 1 + nb_row_to_add

  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  if (isTRUE(fusion)) {
    mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = row_source)
  }
  writeData(classeur, nom_feuille, paste("Source :",source), startCol = col_debut, startRow = row_source)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_source, rows = row_source, cols = col_debut)
}

#' Ajouter un tableau dans une feuille excel
#'
#' Cette fonction crée une nouvelle feuille dans le classeur passé en paramètre et y insère un tableau mis en forme.
#'
#' @param classeur workbook créé avec openXLSX
#' @param tableau dataframe ou tibble à insérer dans une nouvelle feuille
#' @param nom_feuille nom de la nouvelle feuille
#' @param ligne_debut la ligne à laquelle démarre le tableau
#' @param col_debut la colonne à laquelle démarre le tableau
#' 
#' @return Rien n'est renvoyé mais l'objet classeur a une nouvelle feuille
#' 
#' @importFrom openxlsx addWorksheet
#' @importFrom openxlsx writeData
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_tableau_excel <- function(classeur, tableau, nom_feuille, ligne_debut = 3, col_debut = 2) {

  assert_that(class(classeur)=="Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.data.frame(tableau),
              msg = "Le tableau doit \u00eatre un dataframe ou un tibble.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(ligne_debut > 0,
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(ligne_debut),
              msg = "La ligne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  addWorksheet(wb = classeur,
               sheetName = nom_feuille)
  writeData(wb = classeur,
            sheet = nom_feuille,
            x = tableau,
            startCol = col_debut,
            startRow = ligne_debut)
}

#' Ajouter le titre du primeur dans la première cellule de chaque feuille
#'
#' Cette fonction permet d'ajouter le titre en haut de chaque feuille 
#' d'un classeur de type primeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param titre le titre à ajouter
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_titre_primeur <- function(classeur,
                                  titre,
                                  col_debut = 2,
                                  fusion = TRUE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(titre),
              msg = "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  
  liste_style = creer_liste_style_excel(format = "primeur")
  style_titre_primeur = liste_style$titre_primeur
  
  write_row <- 1 
  
  for (feuille in names(classeur)) {
    if (isTRUE(fusion)) {
      nb_col = ncol(readWorkbook(classeur, sheet = feuille))
      if (!is.null(nb_col)) {
        mergeCells(classeur, feuille, cols = col_debut:(col_debut+nb_col-1), rows = write_row)
      }
    }
    writeData(classeur, feuille, titre, startCol = col_debut, startRow = write_row)
    addStyle(wb = classeur, sheet = feuille, style = style_titre_primeur, rows = write_row, cols = col_debut)
  }
  
  
}

#' Ajouter le titre du tableau dans la première cellule d'une feuille
#'
#' Cette fonction permet d'ajouter un titre dans la cellule A1 d'une feuille
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param titre le titre à ajouter
#' @param col_debut la colonne de départ (2eme par défaut)
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur" 
#' @param fusion LGL si les cellules sont à fusionner ou pas (TRUE par défaut)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx writeData
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx mergeCells
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
ajouter_titre_tableau <- function(classeur,
                                  nom_feuille,
                                  titre,
                                  col_debut = 2,
                                  format = "chiffres_et_donnees",
                                  fusion = TRUE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.string(titre),
              msg = "Le titre doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(format)=="character",
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(class(fusion) == "logical",
              msg = "Le param\u00e8tre fusion doit \u00eatre TRUE ou FALSE.")
  
  liste_style = creer_liste_style_excel(format = format)
  style_titre = liste_style$titre
  
  nb_col = ncol(readWorkbook(classeur, sheet = nom_feuille))
  
  write_row <- 1 + row_to_add_format(format = format)
  
  if (isTRUE(fusion)) {
    if (!is.null(nb_col)) {
      mergeCells(classeur, nom_feuille, cols = col_debut:(col_debut+nb_col-1), rows = write_row )
    }
  }
  writeData(classeur, nom_feuille, titre, startCol = col_debut, startRow = write_row)
  addStyle(wb = classeur, sheet = nom_feuille, style = style_titre, rows = write_row, cols = col_debut)
}



#' Parametrer le tableur excel
#' 
#' Cette fonction permet de créer une liste avec tous les styles utiles aux publications Agreste xlsx
#' @param format le format choisi : "chiffres_et_donnees" ou "primeur"
#'
#' @return une liste avec tous les styles disponibles (objets openxls)
#' @export
#' 
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#'
creer_liste_style_excel <- function(format = "chiffres_et_donnees") {
  assert_that((format %in% c("chiffres_et_donnees", "primeur")), msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  
  options("openxlsx.borderStyle" = "thin")
  options("openxlsx.borderColour" = "black")
  options("openxlsx.dateFormat" = "mm/dd/yyyy")
  options("openxlsx.paperSize" = 9)
  options("openxlsx.orientation" = "portrait")
  
  if (format == "chiffres_et_donnees") {
    font <- "Marianne"
  } else if (format == "primeur") {
    font <- "Calibri"
  }
  
  titleStyle <- createStyle(
    fontName = font,
    fontSize = 11,
    fontColour = "black",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <- list(titre = titleStyle)
  
  titre_primeur_style <- createStyle(
    fontName = font,
    fontSize = 14,
    fontColour = "#548235",
    halign = "left",
    valign = "center",
    textDecoration = "bold",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(titre_primeur = titre_primeur_style))
  
  subtitleStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    textDecoration = "italic",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sous_titre = subtitleStyle))
  
  headerStyle <- switch(
    format,
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      fgFill = "#FF8D7E",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "white",
      halign = "center",
      valign = "center",
      fgFill = "#548235",
      border = "TopBottomLeftRight",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(ligne_titre = headerStyle))

  
  unitsUnifStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    textDecoration = "italic",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(lignes_unite_uniforme = unitsUnifStyle))
  
  unitsDiffStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    textDecoration = "italic",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(lignes_unites_differentes = unitsDiffStyle))
  
  dataStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(texte = dataStyleText))
  
  
  dataStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style, values = c(numerique = dataStyleNum))
  
  dataStyleNumDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.00"
  )
  
  liste_style <-
    append(liste_style, values = c(decimal = dataStyleNumDecimal))
  
  
  dataItalicStyleText <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    indent = 1
  )
  
  liste_style <-
    append(liste_style, values = c(texte_italique = dataItalicStyleText))
  
  
  dataItalicStyleNum <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0"
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_italique = dataItalicStyleNum))
  
  
  dataItalicStyleNumUneDecimal <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "right",
    indent = 1,
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    wrapText = TRUE,
    numFmt = "#,##0.00"
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_italique = dataItalicStyleNumUneDecimal))
  
  
  dataTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(texte_total = dataTotalStyleText))
  
  
  dataTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
    
  
  liste_style <-
    append(liste_style, values = c(numerique_total = dataTotalStyleNum))
  
  
  dataTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#d9d9d9",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      fgFill = "#ff8d7e",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_total = dataTotalStyleNumDecimal))
  
  
  dataSubTotalStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(texte_sous_total = dataSubTotalStyleText))
  
  
  
  dataSubTotalStyleNum <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(numerique_sous_total = dataSubTotalStyleNum))
  
  
  dataSubTotalStyleNumDecimal <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "right",
      valign = "center",
      textDecoration = "bold",
      wrapText = TRUE,
      numFmt = "#,##0.00",
      indent = 1
    )
  )
  
  liste_style <-
    append(liste_style,
           values = c(decimal_sous_total = dataSubTotalStyleNumDecimal))
  
  
  dataPrecisionStyleText1 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 1,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_1 = dataPrecisionStyleText1))
  
  dataPrecisionStyleText2 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 2,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_2 = dataPrecisionStyleText2))
    
  dataPrecisionStyleText3 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 3,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_3 = dataPrecisionStyleText3))
  
  dataPrecisionStyleText4 <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    halign = "left",
    valign = "center",
    border = "LeftRight",
    borderColour = "black",
    indent = 4,
    wrapText = TRUE
  )
    
  liste_style <-
    append(liste_style,
           values = c(precision_texte_4 = dataPrecisionStyleText4))
  
  dataSectionStyleText <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "left",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      fgFill = "#c6ddb4",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      halign = "center",
      valign = "center",
      border = "TopBottom",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style, values = c(texte_section = dataSectionStyleText))
  
  
  noteStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    borderColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <- append(liste_style, values = c(note = noteStyle))
  
  sourceStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(source = sourceStyle))
  
  
  champStyle <- createStyle(
    fontName = font,
    fontSize = 9,
    fontColour = "black",
    textDecoration = "italic",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(champ = champStyle))
  
  sommaireChapitreStyle <- switch(format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 11,
      fontColour = "white",
      halign = "left",
      valign = "center",
      fgFill = "#548235",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 11,
      fontColour = "black",
      halign = "left",
      valign = "center",
      fgFill = "#FF8D7E",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
  
  
  liste_style <-
    append(liste_style,
           values = c(sommaire_chapitre = sommaireChapitreStyle))
  
  sommaireSousChapitreStyle <- switch (format,
    "primeur" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      indent = 1,
      halign = "left",
      valign = "center",
      fgFill = "#d9d9d9",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    ),
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 10,
      fontColour = "black",
      indent = 1,
      halign = "left",
      valign = "center",
      fgFill = "#FFE2DB",
      borderColour = "black",
      textDecoration = "bold",
      wrapText = TRUE
    )
  )
    
    createStyle(
    
  )

  liste_style <-
    append(liste_style,
           values = c(sommaire_sous_chapitre = sommaireSousChapitreStyle))
  
  
  sommaireSheetStyle <- createStyle(
    fontName = font,
    fontSize = 10,
    fontColour = "black",
    indent = 3,
    halign = "left",
    valign = "center",
    wrapText = TRUE
  )
  
  liste_style <-
    append(liste_style, values = c(sommaire_lien = sommaireSheetStyle))
  
  
  retourSommaireSheetStyle <- switch (format,
    "chiffres_et_donnees" = createStyle(
      fontName = font,
      fontSize = 11,
      fontColour = "black",
      halign = "center",
      valign = "center",
      fgFill = "#FF8D7E",
      wrapText = TRUE
    ),
    "primeur" = createStyle(
      fontName = font,
      fontSize = 11,
      fontColour = "white",
      halign = "center",
      valign = "center",
      fgFill = "#548235",
      wrapText = TRUE
    )
  )
    
    
    
  liste_style <-
    append(liste_style,
           values = c(bouton_retour_sommaire = retourSommaireSheetStyle))
  
  return(liste_style)
  
}


#' Formater un classeur 
#'
#' @param classeur workbook créé avec openXLSX
#' @param start_row_tabs la ligne de départ des tableaux
#' @param styles une liste de Styles
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque feuille 
#' avec une note de lecture
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre LIST liste des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision_1 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 1
#' @param liste_lignes_precision_2 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 2
#' @param liste_lignes_precision_3 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 3
#' @param liste_lignes_precision_4 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 4
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param liste_unif_unites VEC un vecteur de valeurs logiques pour indiquer 
#' les feuilles ayant des unités de colonnes différentes
#' @param liste_cellules_fusion LIST la liste des cellules à fusionner
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param format CHAR le format entre "chiffres_et_donnees" ou "primeur"
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' @noRd
formater <- function(classeur,
                     start_row_tabs,
                     styles,
                     liste_feuilles_avec_note,
                     liste_type_donnees,
                     liste_lignes_titre,
                     liste_lignes_section,
                     liste_lignes_sous_total,
                     liste_lignes_precision_1,
                     liste_lignes_precision_2,
                     liste_lignes_precision_3,
                     liste_lignes_precision_4,
                     liste_lignes_total,
                     liste_unif_unites,
                     liste_cellules_fusion,
                     format,
                     col_debut = 2,
                     avec_titre = FALSE) {
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  ligne_supp_debut_cd <- switch (format,
        "chiffres_et_donnees" = 1,
        "primeur" = 0
      )
  header_start = start_row_tabs
  start_row_tabs = start_row_tabs + ligne_supp_debut_cd
  
  style_section <- styles$texte_section
  style_precision_1 <- styles$precision_texte_1
  style_precision_2 <- styles$precision_texte_2
  style_precision_3 <- styles$precision_texte_3
  style_precision_4 <- styles$precision_texte_4
  i <- 0
  for (feuille in names(classeur)) {
    i <- i + 1
    max_ligne_titre <- max(liste_lignes_titre[[i]])
    if (isTRUE(liste_unif_unites[i])) {
      shift_rows <- 0
      if (format == "chiffres_et_donnees") {
        shift_headers <- 1
      } else {
        shift_headers <- 0
      }
      
    } else {
      shift_headers <- 0
      if (format == "primeur") {
        shift_rows <- 1
      } else {
        shift_rows <- 0
      }
    }
    nb_col <- ncol(readWorkbook(classeur, sheet = feuille))
    last_row <- nrow(readWorkbook(classeur, sheet = feuille, skipEmptyRows = FALSE, colNames = FALSE))
    if (feuille %in% liste_feuilles_avec_note) {
      eff_last_row <- last_row - 4 + nb_row_to_add
    } else {
      eff_last_row <- last_row - 3 + nb_row_to_add
    }
    for (line in liste_lignes_titre[[i]]) {
      addStyle(wb = classeur,
             sheet = feuille,
             style = styles$ligne_titre,
             rows = line + header_start + shift_headers - 1,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
    }
    
  
    for (num_col in col_debut:(nb_col + col_debut - 1)) {
      j <- num_col - col_debut + 1
  
      assert_that(liste_type_donnees[[i]][j] %in% c("texte", "numerique", "decimal"),
                  msg = paste("Format de donn\u00e9es", liste_type_donnees[[i]][j], "non valide."))
  
      style_data <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte,
        "numerique" = styles$numerique,
        "decimal" = styles$decimal
      )
      style_sous_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_sous_total,
        "numerique" = styles$numerique_sous_total,
        "decimal" = styles$decimal_sous_total
      )
      style_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_total,
        "numerique" = styles$numerique_total,
        "decimal" = styles$decimal_total
      )
      r <- 0
      col_data = readWorkbook(xlsxFile = classeur,
                              sheet = feuille,
                              rows = (start_row_tabs + max_ligne_titre + shift_rows):eff_last_row,
                              cols = num_col, 
                              colNames = FALSE)$X1
      for (row in (start_row_tabs + max_ligne_titre + shift_rows):eff_last_row) {
        r <- r + 1
        if (liste_type_donnees[[i]][j] %in% c("numerique", "decimal")) {
          if (class(col_data[r]) != "numeric") {
            if ((substr(col_data[r], 1, 1) %in% c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")) | ((nchar(col_data[r]) >= 2) & (substr(col_data[r], 1, 2) %in% c("-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9")))) {
              x <- as.numeric(col_data[r])
              writeData(wb = classeur, 
                        sheet = feuille,
                        x = x,
                        startCol = num_col,
                        startRow = row)
            }
          }
        }
      }
      
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_data,
               rows = ((start_row_tabs + max_ligne_titre + shift_rows):eff_last_row),
               cols = num_col,
               stack = TRUE)
      if (!(0 %in% liste_lignes_sous_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_sous_total,
               rows = liste_lignes_sous_total[[i]] + start_row_tabs + shift_rows,
               cols = num_col,
               stack = TRUE)
      }
      
      if (!(0 %in% liste_lignes_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_total,
               rows = liste_lignes_total[[i]] + start_row_tabs + shift_rows,
               cols = num_col,
               stack = TRUE)
      }
      
    }
    if ((eff_last_row - start_row_tabs - shift_rows) %in% liste_lignes_total[[i]]) {
      if (format == "chiffres_et_donnees") {
        addStyle(wb = classeur,
             sheet = feuille,
             style = createStyle(border = "top",
                                 borderColour = "black"),
             rows = eff_last_row,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
      }
    }
    
    addStyle(wb = classeur,
             sheet = feuille,
             style = createStyle(border = "bottom",
                                 borderColour = "black"),
             rows = eff_last_row,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
    
    if (!(0 %in% liste_lignes_precision_1[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_1,
               rows = liste_lignes_precision_1[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_2[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_2,
               rows = liste_lignes_precision_2[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_3[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_3,
               rows = liste_lignes_precision_3[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_4[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_4,
               rows = liste_lignes_precision_4[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_section[[i]])) {
      for (row_n in liste_lignes_section[[i]] + start_row_tabs + shift_rows) {
        for (col_n in col_debut:(nb_col + col_debut - 1)) {
          addStyle(wb = classeur,
               sheet = feuille,
               style = style_section,
               rows = row_n,
               cols = col_n,
               stack = TRUE)
        }
      }
      
      for (merge_row in liste_lignes_section[[i]]) {
        mergeCells(wb = classeur,
                 sheet = feuille,
                 cols = col_debut:(nb_col + col_debut - 1),
                 rows = merge_row + start_row_tabs - max_ligne_titre + shift_rows + 1)
      }
      
    }
    
    if (!(0 %in% liste_cellules_fusion[[i]])) {
      for (step1 in liste_cellules_fusion[[i]]) {
      step2 <- unlist(strsplit(step1, split = ";"))
      assert_that(length(step2) == 2,
                  msg = paste("Probl\u00e8me dans la colonne Cellules_a_fusionner, tableau ",
                              i,
                              ". Veuillez la v\u00e9rifier.",
                              sep = ""))
      l_row = eval(parse(text = substr(step2[1], 2, nchar(step2[1]))))
      if (l_row[1] %in% liste_lignes_titre[[i]]) {
        rows = l_row + header_start + shift_headers - 1
      } else {
        rows <- l_row + start_row_tabs + shift_rows - 1
      }
      cols <- eval(parse(text = substr(step2[2], 1, nchar(step2[2]) - 1))) + col_debut - 1
      mergeCells(wb = classeur,
                 sheet = feuille,
                 cols = cols,
                 rows = rows)
      }
    }
    
    }
}

#' Formater un classeur entier
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi
#'
#' @param classeur workbook créé avec openXLSX
#' @param format CHAR le type de publication : 
#' "chiffres_et_donnees" ou "primeur"
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque 
#' feuille avec une note de lecture
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre LIST liste des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision_1 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 1
#' @param liste_lignes_precision_2 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 2
#' @param liste_lignes_precision_3 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 3
#' @param liste_lignes_precision_4 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 4
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param liste_unif_unites VEC un vecteur de valeurs logiques pour indiquer 
#' les feuilles ayant des unités de colonnes différentes
#' @param liste_cellules_fusion LIST la liste des cellules à fusionner
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' @importFrom readr parse_number
#' @importFrom readr locale
#' 
#' @export
#'
formater_auto <- function(classeur,
                          format,
                          liste_feuilles_avec_note,
                          liste_type_donnees,
                          liste_lignes_titre,
                          liste_lignes_section,
                          liste_lignes_sous_total,
                          liste_lignes_precision_1,
                          liste_lignes_precision_2,
                          liste_lignes_precision_3,
                          liste_lignes_precision_4,
                          liste_lignes_total,
                          liste_unif_unites,
                          liste_cellules_fusion,
                          col_debut = 2,
                          avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  if (!is.null(liste_feuilles_avec_note)) {
    assert_that(class(liste_feuilles_avec_note) == "character",
              msg = "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
    for (feuille in liste_feuilles_avec_note) {
    assert_that(feuille %in% names(classeur),
                msg = paste("La feuille", feuille, "n'est pas une feuille existante."))
    }
  }

  
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  for(i in 1:length(liste_type_donnees)) {
    assert_that(class(liste_type_donnees[[i]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  }
  assert_that(class(liste_lignes_titre) == "list",
              msg = "La liste des lignes de titre doit \u00eatre de type list.")
  assert_that(class(liste_lignes_section) == "list",
              msg = "La liste des lignes de section doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_section[[i]]) == "numeric",
              msg = "La liste des lignes de section doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_sous_total) == "list",
              msg = "La liste des lignes de sous-total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_sous_total)) {
    assert_that(class(liste_lignes_sous_total[[i]]) == "numeric",
              msg = "La liste des lignes de sous-total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_precision_1) == "list",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_precision_1[[i]]) == "numeric",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_total) == "list",
              msg = "La liste des lignes de total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_total)) {
    assert_that(class(liste_lignes_total[[i]]) == "numeric",
              msg = "La liste des lignes de total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  mes_styles <- creer_liste_style_excel(format = format)
  
  nb_row_to_add <- row_to_add_format(format = format)
  
  formater(classeur = classeur, 
           start_row_tabs = 3 + nb_row_to_add, 
           styles = mes_styles,
           liste_feuilles_avec_note = liste_feuilles_avec_note, 
           liste_type_donnees = liste_type_donnees,
           liste_lignes_titre = liste_lignes_titre,
           liste_lignes_section = liste_lignes_section,
           liste_lignes_sous_total = liste_lignes_sous_total,
           liste_lignes_precision_1 = liste_lignes_precision_1,
           liste_lignes_precision_2 = liste_lignes_precision_2,
           liste_lignes_precision_3 = liste_lignes_precision_3,
           liste_lignes_precision_4 = liste_lignes_precision_4,
           liste_lignes_total = liste_lignes_total,
           liste_unif_unites = liste_unif_unites,
           liste_cellules_fusion = liste_cellules_fusion,
           col_debut = col_debut,
           format = format,
           avec_titre = avec_titre)
}

#' Geler une(des) ligne(s) et/ou une(des) colonne(s) 
#'
#' Cette fonction permet de geler une ou plusieurs lignes ainsi qu'une ou plusieurs colonnes d'une feuille de classeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param ligne la ligne à geler (0 si pas de ligne à geler)
#' @param col la colonne à geler (0 si pas de colonne à geler)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx freezePane
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
geler <- function(classeur,
                  nom_feuille,
                  ligne = 0,
                  col = 0) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille),
              msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(ligne >= 0,
              msg = "La ligne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(col >= 0,
              msg = "La colonne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(is.numeric(ligne),
              msg = "La ligne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(is.numeric(col),
              msg = "La colonne \u00e0 geler doit \u00eatre un entier positif.")
  
  ligne <- ligne + 1
  col <- col + 1
  
  freezePane(classeur, nom_feuille, firstActiveRow = ligne, firstActiveCol = col)

}

#' Renvoie le nombre de lignes à ajouter selon le format
#' 
#' @param format CHAR le format choisi entre "chiffres_et_donnees" et "primeur"
#' 
#' @return NUM le nombre de lignes à ajouter
#' @noRd
row_to_add_format <- function(format) {
  if (format == "chiffres_et_donnees") {
    return(0)
  } else {
    return(2)
  }
}

#' Applique des tailles de colonne aux tableaux d'un workbook
#'
#' Cette fonction permet d'appliquer une taille de colonne choisie par 
#' l'utilisateur ou bien automatiquement, 
#' le total étant égal à 83, et les colonnes de texte étant plus larges 
#' que les autres en mode automatique
#'
#' @param classeur Le classeur excel, objet de type workbook
#' @param liste_type_donnees LIST liste de vecteurs contenant 
#' les types de données de chaque colonne
#' @param largeurs LIST liste de vecteurs contenant les largeurs colonne, 
#' "auto" pour appliquer des largeurs automatique
#' @param format CHAR le format de publication : "primeur" ou "chiffres_et_donnees"
#' @param col_debut La colonne à laquelle commencent les tableaux, par défaut 2
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom assertthat assert_that
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx setColWidths
#' @importFrom comprehenr to_vec
#' @importFrom collections dict
#' 
#' @export
#'
taille_colonnes <- function(classeur, liste_type_donnees, largeurs, format, col_debut = 2) {
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  assert_that(class(liste_type_donnees[[1]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  sheets <- names(classeur)
  
  indice_feuille <- 0
  
  pao_max <- 83
  weight_num <- 2
  
  for (sheet in sheets) {
    nb_col <- ncol(readWorkbook(classeur, sheet = sheet))
    indice_feuille <- indice_feuille + 1
    if (largeurs[[indice_feuille]][1] == "auto" | largeurs[[indice_feuille]][1] == 0) {
      types <- liste_type_donnees[[indice_feuille]]
      mean_width <- round(pao_max/nb_col, digits = 2) - 0.01
      nb_text <- sum(to_vec(for(type in types) if(type == "texte") 1))
      nb_num <- nb_col - nb_text
      text_width <- mean_width + nb_num*weight_num/nb_text
      if ("texte" %in% types) {
        num_width <- mean_width - weight_num
      } else {
        num_width <- mean_width
      }
      
      d <- dict(keys = c("texte", "decimal", "numerique"),
                items = c(text_width, num_width, num_width))
      
      widths <- to_vec(for(type in types) d$get(type))
    } else {
      widths <- largeurs[[indice_feuille]]
    }
    
    if (format == "chiffres_et_donnees") {
      assert_that(sum(widths) <= pao_max,
                msg = paste("La largeur du tableau ne doit pas dépasser ",
                            pao_max,
                            ". Largeur actuelle : ",
                            sum(widths), sep = ""))
    }
    
    setColWidths(wb = classeur,
                 sheet = sheet,
                 cols = col_debut:(nb_col + col_debut - 1),
                 widths = widths)
  }
  
}
