# WARNING - Generated by {fusen} from /dev/flat_carte.Rmd: do not edit by hand

#' Créer un tableau avec les données géographiques de fond de carte
#'
#' @return Dataframe avec les données géographiques des zones de la carte
#' @param zone_geographique CHAR indiquant la zone retenue pour la carte : "france", "ue" ou "monde"
#' @param niveau_representation CHAR indiquant le niveau de représentation : "pays", "region_metro" ou "departement_metro"
#' @export
#' @importFrom assertthat assert_that
#' @importFrom sf st_read
#' @importFrom sf st_centroid
#' @importFrom magrittr %>% 
#' @importFrom dplyr select
#' @importFrom dplyr mutate
#' @importFrom dplyr filter
#' @importFrom dplyr recode
#' @importFrom glue glue
#' @importFrom glue glue_collapse
#' @importFrom stringr str_c
#' 
#' @examples
#' data_geo_france_region_metro <- donnees_fond_carte(zone_geographique = "france", niveau_representation = "region_metro")
#' data_geo_france_dep_metro <- donnees_fond_carte(zone_geographique = "france", niveau_representation = "departement_metro")
donnees_fond_carte <- function(zone_geographique = "france",
                               niveau_representation = "region_metro") {
  
### vérification des paramètres d'entrée
  liste_zone_geographique <- c("france", "ue" , "monde")
  liste_niveau_representation <- c("pays", "region_metro", "departement_metro")

  assertthat::assert_that(zone_geographique %in% liste_zone_geographique, 
                          msg = glue("La zone geographique doit etre dans la liste des choix possibles : {glue_collapse(liste_zone_geographique, sep=', ')}."))
  assertthat::assert_that(niveau_representation %in% liste_niveau_representation, 
                          msg = glue("Le niveau de representation geographique doit etre dans la liste des choix possibles : {glue_collapse(liste_niveau_representation, sep=', ')}."))

  
#### récupération de la carte vide 
  data_geo <- agreste::data_geo

#### restriction à la zone géographique
code_zone_geographique <- switch (zone_geographique,
  "france" = "FR",
  "ue" = "",
  "monde" = ""
)
  
data_geo <- data_geo %>% 
  filter(CNTR_CODE == code_zone_geographique)

#### limitation au niveau de représentation 
code_niveau_representation <- switch (niveau_representation,
  "pays" = 0 ,
  "region_metro" = 1,
  "departement_metro" = 3
)
# FRY : Code NUTS des DOM
exclusion_formes <- switch (niveau_representation,
  "pays" = "",
  "region_metro" = c("FR", "FRY", "FRY1", "FRY2", "FRY3", "FRY4", "FRY5", "FRY10", "FRY20", "FRY30", "FRY40", "FRY50"),
  "departement_metro" = c("FRY10", "FRY20", "FRY30", "FRY40", "FRY50")
)

data_geo <- data_geo %>% 
  filter(LEVL_CODE == code_niveau_representation & 
           !NUTS_ID %in% exclusion_formes )

##### affectation n° de région et n° de département
codes_regions <- c("FRI" = "75",
                   "FRJ" = "76",
                   "FRK" = "84",
                   "FRL" = "93",
                   "FRM" = "94",
                   "FR1" = "11",
                   "FRB" = "24",
                   "FRC" = "27",
                   "FRD" = "28",
                   "FRE" = "32",
                   "FRF" = "44",
                   "FRG" = "52",
                   "FRH" = "53"
)

codes_departements <- c("FRK21" = "01",
                        "FRE21" = "02",
                        "FRK11" = "03",
                        "FRL01" = "04",
                        "FRL03" = "06",
                        "FRK22" = "07",
                        "FRF21" = "08",
                        "FRJ21" = "09",
                        "FRF22" = "10",
                        "FRJ11" = "11",
                        "FRJ22" = "12",
                        "FRF11" = "67",
                        "FRL04" = "13",
                        "FRD11" = "14",
                        "FRK12" = "15",
                        "FRI31" = "16",
                        "FRI32" = "17",
                        "FRB01" = "18",
                        "FRI21" = "19",
                        "FRM01" = "2A",
                        "FRC11" = "21",
                        "FRH01" = "22",
                        "FRI22" = "23",
                        "FRI33" = "79",
                        "FRI11" = "24",
                        "FRC21" = "25",
                        "FRK23" = "26",
                        "FR104" = "91",
                        "FRD21" = "27",
                        "FRB02" = "28",
                        "FRH02" = "29",
                        "FRJ12" = "30",
                        "FRJ24" = "32",
                        "FRI12" = "33",
                        "FRF12" = "68",
                        "FRM02" = "2B",
                        "FRJ23" = "31",
                        "FRK13" = "43",
                        "FRF24" = "52",
                        "FRC23" = "70",
                        "FRK28" = "74",
                        "FRI23" = "87",
                        "FRL02" = "05",
                        "FRJ26" = "65",
                        "FR105" = "92",
                        "FRJ13" = "34",
                        "FRH03" = "35",
                        "FRB03" = "36",
                        "FRB04" = "37",
                        "FRK24" = "38",
                        "FRC22" = "39",
                        "FRI13" = "40",
                        "FRB05" = "41",
                        "FRK25" = "42",
                        "FRG01" = "44",
                        "FRB06" = "45",
                        "FRJ25" = "46",
                        "FRI14" = "47",
                        "FRJ14" = "48",
                        "FRG02" = "49",
                        "FRD12" = "50",
                        "FRF23" = "51",
                        "FRG03" = "53",
                        "FRF31" = "54",
                        "FRF32" = "55",
                        "FRH04" = "56",
                        "FRF33" = "57",
                        "FRC12" = "58",
                        "FRE11" = "59",
                        "FRE22" = "60",
                        "FRD13" = "61",
                        "FR101" = "75",
                        "FRE12" = "62",
                        "FRK14" = "63",
                        "FRI15" = "64",
                        "FRJ15" = "66",
                        "FRK26" = "69",
                        "FRC13" = "71",
                        "FRG04" = "72",
                        "FRK27" = "73",
                        "FR102" = "77",
                        "FRD22" = "76",
                        "FR106" = "93",
                        "FRE23" = "80",
                        "FRJ27" = "81",
                        "FRJ28" = "82",
                        "FRC24" = "90",
                        "FR108" = "95",
                        "FR107" = "94",
                        "FRL05" = "83",
                        "FRL06" = "84",
                        "FRG05" = "85",
                        "FRI34" = "86",
                        "FRF34" = "88",
                        "FRC14" = "89",
                        "FR103" = "78"
                        )

data_geo <- data_geo %>% 
  mutate(code_region = recode(NUTS_ID, !!!codes_regions))

data_geo <- data_geo %>% 
  mutate(code_dep = recode(NUTS_ID, !!!codes_departements))
### calcul des centroids

data_geo <- data_geo %>% 
  mutate(centre=st_centroid(geometry)) 
  
### renvoie le dataframe
return(data_geo)
  
}
