# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Formater un classeur entier
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi
#'
#' @param classeur workbook créé avec openXLSX
#' @param format CHAR le type de publication : "chiffres_et_donnees" ou "primeur"
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque feuille avec une note de lecture
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de données de chaque colonne
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples

#' library(openxlsx)
#' library(agreste)
#' 
#' ## Création d'un classeur avec deux feuilles et deux tableaux
#' mon_classeur <- createWorkbook()
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = iris,
#'                       nom_feuille = "iris",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "iris",
#'                       titre = "Données fleurs iris",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "iris",
#'                source = "Ceci est une source quelconque",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = FALSE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "iris",
#'               champ = "France métropolitaine",
#'               format = "primeur",
#'               col_debut = 2)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = airquality,
#'                       nom_feuille = "airquality",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "airquality",
#'                       titre = "Données qualité de l'air",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_note_lecture(classeur = mon_classeur,
#'                      nom_feuille = "airquality",
#'                      note = "blablabla",
#'                      format = "primeur",
#'                      col_debut = 2)
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "airquality",
#'                source = "Eurostat",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = TRUE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "airquality",
#'               champ = "Daily air quality measurements in New York, May to September 1973.",
#'               format = "primeur",
#'               col_debut = 2)
#' 
#' ## Formater comme un Chiffres et Données
#' formater_auto(mon_classeur,
#'               format = "primeur",
#'               liste_feuilles_avec_note = c("airquality"),
#'               liste_type_donnees = list(c("decimal",
#'                                           "decimal",
#'                                           "decimal",
#'                                           "decimal",
#'                                           "texte"),
#'                                         c("numerique",
#'                                           "numerique",
#'                                           "decimal",
#'                                           "numerique",
#'                                           "numerique",
#'                                           "numerique")),
#'               col_debut = 2)
#' 
#' ## Sauver
#' saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
#' 
#' ## Ouvrir
#' browseURL("tableau.xlsx")
#' 
formater_auto <- function(classeur,
                          format,
                          liste_feuilles_avec_note,
                          liste_type_donnees,
                          col_debut = 2) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(class(liste_feuilles_avec_note) == "character",
              msg = "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  assert_that(class(liste_type_donnees[[1]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  
  mes_styles <- creer_liste_style_excel(format = format)
  
  nb_row_to_add <- switch (format,
    "chiffres_et_donnees" = 0,
    "primeur" = 2
  )
  
  formater <- function(classeur, start_row_tabs, liste_feuilles_avec_note, liste_type_donnees, mes_styles, col_debut) {
    
    i <- 0
    for (feuille in names(classeur)) {
      i <- i + 1
      nb_col <- ncol(readWorkbook(classeur, sheet = feuille))
      last_row <- nrow(readWorkbook(classeur, sheet = feuille, skipEmptyRows = FALSE, colNames = FALSE))
      if (feuille %in% liste_feuilles_avec_note) {
        eff_last_row <- last_row - 4 + nb_row_to_add
      } else {
        eff_last_row <- last_row - 3 + nb_row_to_add
      }
      
      addStyle(wb = classeur,
               sheet = feuille,
               style = mes_styles$ligne_titre,
               rows = start_row_tabs,
               cols = col_debut:(nb_col + col_debut - 1))

      for (num_col in col_debut:(nb_col + col_debut - 1)) {
        j <- num_col - col_debut + 1

        assert_that(liste_type_donnees[[i]][j] %in% c("texte", "numerique", "decimal"),
                    msg = paste("Format de donn\u00e9es", liste_type_donnees[[i]][j], "non valide."))

        style <- switch (liste_type_donnees[[i]][j],
          "texte" = mes_styles$texte,
          "numerique" = mes_styles$numerique,
          "decimal" = mes_styles$decimal
        )
        
        addStyle(wb = classeur,
                 sheet = feuille,
                 style = style,
                 rows = (start_row_tabs + 1):eff_last_row,
                 cols = num_col)
        
      }
      addStyle(wb = classeur,
               sheet = feuille,
               style = createStyle(border = "bottom",
                                   borderColour = "black"),
               rows = eff_last_row,
               cols = col_debut:(nb_col + col_debut - 1),
               stack = TRUE)
    }
  }
  
  if (format == "chiffres_et_donnees") {
    formater(classeur, 3, liste_feuilles_avec_note, liste_type_donnees, mes_styles, col_debut)
  } else if (format == "primeur") {
    formater(classeur, 5, liste_feuilles_avec_note, liste_type_donnees, mes_styles, col_debut)
  }
  
}
