# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Formater un classeur 
#'
#' @param classeur workbook créé avec openXLSX
#' @param start_row_tabs la ligne de départ des tableaux
#' @param styles une liste de Styles
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque feuille 
#' avec une note de lecture
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre LIST liste des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision_1 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 1
#' @param liste_lignes_precision_2 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 2
#' @param liste_lignes_precision_3 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 3
#' @param liste_lignes_precision_4 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 4
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param liste_unif_unites VEC un vecteur de valeurs logiques pour indiquer 
#' les feuilles ayant des unités de colonnes différentes
#' @param liste_cellules_fusion LIST la liste des cellules à fusionner
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param format CHAR le format entre "chiffres_et_donnees" ou "primeur"
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' @noRd
formater <- function(classeur,
                     start_row_tabs,
                     styles,
                     liste_feuilles_avec_note,
                     liste_type_donnees,
                     liste_lignes_titre,
                     liste_lignes_section,
                     liste_lignes_sous_total,
                     liste_lignes_precision_1,
                     liste_lignes_precision_2,
                     liste_lignes_precision_3,
                     liste_lignes_precision_4,
                     liste_lignes_total,
                     liste_unif_unites,
                     liste_cellules_fusion,
                     format,
                     col_debut = 2,
                     avec_titre = FALSE) {
  
  if (avec_titre == TRUE) {
    nb_row_to_add <- 0
  } else {
    nb_row_to_add <- row_to_add_format(format = format)
  }
  
  ligne_supp_debut_cd <- switch (format,
        "chiffres_et_donnees" = 1,
        "primeur" = 0
      )
  header_start = start_row_tabs
  start_row_tabs = start_row_tabs + ligne_supp_debut_cd
  
  style_section <- styles$texte_section
  style_precision_1 <- styles$precision_texte_1
  style_precision_2 <- styles$precision_texte_2
  style_precision_3 <- styles$precision_texte_3
  style_precision_4 <- styles$precision_texte_4
  i <- 0
  for (feuille in names(classeur)) {
    i <- i + 1
    max_ligne_titre <- max(liste_lignes_titre[[i]])
    if (isTRUE(liste_unif_unites[i])) {
      shift_rows <- 0
      if (format == "chiffres_et_donnees") {
        shift_headers <- 1
      } else {
        shift_headers <- 0
      }
      
    } else {
      shift_headers <- 0
      if (format == "primeur") {
        shift_rows <- 1
      } else {
        shift_rows <- 0
      }
    }
    nb_col <- ncol(readWorkbook(classeur, sheet = feuille))
    last_row <- nrow(readWorkbook(classeur, sheet = feuille, skipEmptyRows = FALSE, colNames = FALSE))
    if (feuille %in% liste_feuilles_avec_note) {
      eff_last_row <- last_row - 4 + nb_row_to_add
    } else {
      eff_last_row <- last_row - 3 + nb_row_to_add
    }
    for (line in liste_lignes_titre[[i]]) {
      addStyle(wb = classeur,
             sheet = feuille,
             style = styles$ligne_titre,
             rows = line + header_start + shift_headers - 1,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
    }
    
  
    for (num_col in col_debut:(nb_col + col_debut - 1)) {
      j <- num_col - col_debut + 1
  
      assert_that(liste_type_donnees[[i]][j] %in% c("texte", "numerique", "decimal"),
                  msg = paste("Format de donn\u00e9es", liste_type_donnees[[i]][j], "non valide."))
  
      style_data <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte,
        "numerique" = styles$numerique,
        "decimal" = styles$decimal
      )
      style_sous_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_sous_total,
        "numerique" = styles$numerique_sous_total,
        "decimal" = styles$decimal_sous_total
      )
      style_total <- switch (liste_type_donnees[[i]][j],
        "texte" = styles$texte_total,
        "numerique" = styles$numerique_total,
        "decimal" = styles$decimal_total
      )
      r <- 0
      col_data = readWorkbook(xlsxFile = classeur,
                              sheet = feuille,
                              rows = (start_row_tabs + max_ligne_titre + shift_rows):eff_last_row,
                              cols = num_col, 
                              colNames = FALSE)$X1
      for (row in (start_row_tabs + max_ligne_titre + shift_rows):eff_last_row) {
        r <- r + 1
        if (liste_type_donnees[[i]][j] %in% c("numerique", "decimal")) {
          if (class(col_data[r]) != "numeric") {
            if ((substr(col_data[r], 1, 1) %in% c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")) | ((nchar(col_data[r]) >= 2) & (substr(col_data[r], 1, 2) %in% c("-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9")))) {
              x <- as.numeric(col_data[r])
              writeData(wb = classeur, 
                        sheet = feuille,
                        x = x,
                        startCol = num_col,
                        startRow = row)
            }
          }
        }
      }
      
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_data,
               rows = ((start_row_tabs + max_ligne_titre + shift_rows):eff_last_row),
               cols = num_col,
               stack = TRUE)
      if (!(0 %in% liste_lignes_sous_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_sous_total,
               rows = liste_lignes_sous_total[[i]] + start_row_tabs + shift_rows,
               cols = num_col,
               stack = TRUE)
      }
      
      if (!(0 %in% liste_lignes_total[[i]])) {
        addStyle(wb = classeur,
               sheet = feuille,
               style = style_total,
               rows = liste_lignes_total[[i]] + start_row_tabs + shift_rows,
               cols = num_col,
               stack = TRUE)
      }
      
    }
    if ((eff_last_row - start_row_tabs - shift_rows) %in% liste_lignes_total[[i]]) {
      if (format == "chiffres_et_donnees") {
        addStyle(wb = classeur,
             sheet = feuille,
             style = createStyle(border = "top",
                                 borderColour = "black"),
             rows = eff_last_row,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
      }
    }
    
    addStyle(wb = classeur,
             sheet = feuille,
             style = createStyle(border = "bottom",
                                 borderColour = "black"),
             rows = eff_last_row,
             cols = col_debut:(nb_col + col_debut - 1),
             stack = TRUE)
    
    if (!(0 %in% liste_lignes_precision_1[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_1,
               rows = liste_lignes_precision_1[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_2[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_2,
               rows = liste_lignes_precision_2[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_3[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_3,
               rows = liste_lignes_precision_3[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_precision_4[[i]])) {
      addStyle(wb = classeur,
               sheet = feuille,
               style = style_precision_4,
               rows = liste_lignes_precision_4[[i]] + start_row_tabs + shift_rows,
               cols = col_debut,
               stack = TRUE)
    }
    
    if (!(0 %in% liste_lignes_section[[i]])) {
      for (row_n in liste_lignes_section[[i]] + start_row_tabs + shift_rows) {
        for (col_n in col_debut:(nb_col + col_debut - 1)) {
          addStyle(wb = classeur,
               sheet = feuille,
               style = style_section,
               rows = row_n,
               cols = col_n,
               stack = TRUE)
        }
      }
      
      for (merge_row in liste_lignes_section[[i]]) {
        mergeCells(wb = classeur,
                 sheet = feuille,
                 cols = col_debut:(nb_col + col_debut - 1),
                 rows = merge_row + start_row_tabs - max_ligne_titre + shift_rows + 1)
      }
      
    }
    
    if (!(0 %in% liste_cellules_fusion[[i]])) {
      for (step1 in liste_cellules_fusion[[i]]) {
      step2 <- unlist(strsplit(step1, split = ";"))
      assert_that(length(step2) == 2,
                  msg = paste("Probl\u00e8me dans la colonne Cellules_a_fusionner, tableau ",
                              i,
                              ". Veuillez la v\u00e9rifier.",
                              sep = ""))
      l_row = eval(parse(text = substr(step2[1], 2, nchar(step2[1]))))
      if (l_row[1] %in% liste_lignes_titre[[i]]) {
        rows = l_row + header_start + shift_headers - 1
      } else {
        rows <- l_row + start_row_tabs + shift_rows - 1
      }
      cols <- eval(parse(text = substr(step2[2], 1, nchar(step2[2]) - 1))) + col_debut - 1
      mergeCells(wb = classeur,
                 sheet = feuille,
                 cols = cols,
                 rows = rows)
      }
    }
    
    }
}

#' Formater un classeur entier
#'
#' Cette fonction permet de formater tous les tableaux d'un classeur selon le type de publication choisi
#'
#' @param classeur workbook créé avec openXLSX
#' @param format CHAR le type de publication : 
#' "chiffres_et_donnees" ou "primeur"
#' @param liste_feuilles_avec_note vecteur contenant le nom de chaque 
#' feuille avec une note de lecture
#' @param col_debut NUM la colonne à laquelle les tableaux démarrent
#' @param liste_type_donnees LIST liste de vecteurs contenant les types de 
#' données de chaque colonne
#' @param liste_lignes_titre LIST liste des lignes de titres de colonnes 
#' @param liste_lignes_section LIST liste de vecteurs contenant les numéros des 
#' lignes du tableau qui sont des sections
#' @param liste_lignes_sous_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des sous-totaux
#' @param liste_lignes_precision_1 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 1
#' @param liste_lignes_precision_2 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 2
#' @param liste_lignes_precision_3 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 3
#' @param liste_lignes_precision_4 LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de précision de niveau 4
#' @param liste_lignes_total LIST liste des vecteurs contenant les numéros
#' des lignes du tableau qui sont des lignes de totaux
#' @param liste_unif_unites VEC un vecteur de valeurs logiques pour indiquer 
#' les feuilles ayant des unités de colonnes différentes
#' @param liste_cellules_fusion LIST la liste des cellules à fusionner
#' @param avec_titre LGL si le classeur est un primeur avec un titre
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom openxlsx addStyle
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx createStyle
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' @importFrom readr parse_number
#' @importFrom readr locale
#' 
#' @export
#'
#' @examples
#' library(openxlsx)
#' library(agreste)
#' 
#' ## Création d'un classeur avec deux feuilles et deux tableaux
#' mon_classeur <- createWorkbook()
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = iris,
#'                       nom_feuille = "iris",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "iris",
#'                       titre = "Données fleurs iris",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "iris",
#'                source = "Ceci est une source quelconque",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = FALSE,
#'                avec_titre = FALSE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "iris",
#'               champ = "France métropolitaine",
#'               format = "primeur",
#'               col_debut = 2,
#'               avec_titre = FALSE)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = airquality,
#'                       nom_feuille = "airquality",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "airquality",
#'                       titre = "Données qualité de l'air",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_note_lecture(classeur = mon_classeur,
#'                      nom_feuille = "airquality",
#'                      note = "blablabla",
#'                      format = "primeur",
#'                      col_debut = 2,
#'                      avec_titre = FALSE)
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "airquality",
#'                source = "Eurostat",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = TRUE,
#'                avec_titre = FALSE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "airquality",
#'               champ = "Daily air quality measurements in New York, May to September 1973.",
#'               format = "primeur",
#'               col_debut = 2,
#'               avec_titre = FALSE)
#' 
#' ajouter_titre_primeur(classeur = mon_classeur,
#'                       titre = "Exemple 2022")
#' 
#' taille_colonnes(classeur = mon_classeur,
#'                 liste_type_donnees = list(c("decimal",
#'                                             "decimal",
#'                                             "decimal",
#'                                             "decimal",
#'                                             "texte"),
#'                                           c("numerique",
#'                                             "numerique",
#'                                             "decimal",
#'                                             "numerique",
#'                                             "numerique",
#'                                             "numerique")),
#'                 largeurs = list(c("auto"), c("auto")),
#'                 format = "primeur",
#'                 col_debut = 2)
#' 
#' ## Formater comme un Primeur
#' formater_auto(classeur = mon_classeur,
#'               format = "primeur",
#'               liste_feuilles_avec_note = c("airquality"),
#'               liste_type_donnees = list(c("decimal",
#'                                           "decimal",
#'                                           "decimal",
#'                                           "decimal",
#'                                           "texte"),
#'                                         c("numerique",
#'                                           "numerique",
#'                                           "decimal",
#'                                           "numerique",
#'                                           "numerique",
#'                                           "numerique")), 
#'               liste_lignes_titre = list(c(1), c(1)),
#'               liste_lignes_section = list(c(5, 9),
#'                                           c(3, 8)),
#'               liste_lignes_sous_total = list(c(4, 8),
#'                                              c(2, 7)),
#'               liste_lignes_precision_1 = list(c(2,3),
#'                                             c(0)),
#'               liste_lignes_precision_2 = list(c(0), c(0)),
#'               liste_lignes_precision_3 = list(c(0), c(0)),
#'               liste_lignes_precision_4 = list(c(0), c(0)),
#'               liste_lignes_total = list(c(150),
#'                                         c(100)),
#'               liste_unif_unites = c(TRUE, TRUE),
#'               liste_cellules_fusion = list(c(0), c(0)),
#'               col_debut = 2,
#'               avec_titre = TRUE)
#' 
#' ## Sauver
#' saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
#' 
#' ## Ouvrir
#' browseURL("tableau.xlsx")
#' 
formater_auto <- function(classeur,
                          format,
                          liste_feuilles_avec_note,
                          liste_type_donnees,
                          liste_lignes_titre,
                          liste_lignes_section,
                          liste_lignes_sous_total,
                          liste_lignes_precision_1,
                          liste_lignes_precision_2,
                          liste_lignes_precision_3,
                          liste_lignes_precision_4,
                          liste_lignes_total,
                          liste_unif_unites,
                          liste_cellules_fusion,
                          col_debut = 2,
                          avec_titre = FALSE) {
  
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  if (!is.null(liste_feuilles_avec_note)) {
    assert_that(class(liste_feuilles_avec_note) == "character",
              msg = "La liste des feuilles contenant une note de lecture doit \u00eatre un vecteur contenant des cha\u00eenes de caract\u00e8res.")
    for (feuille in liste_feuilles_avec_note) {
    assert_that(feuille %in% names(classeur),
                msg = paste("La feuille", feuille, "n'est pas une feuille existante."))
    }
  }

  
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  for(i in 1:length(liste_type_donnees)) {
    assert_that(class(liste_type_donnees[[i]]) == "character",
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re.")
  }
  assert_that(class(liste_lignes_titre) == "list",
              msg = "La liste des lignes de titre doit \u00eatre de type list.")
  assert_that(class(liste_lignes_section) == "list",
              msg = "La liste des lignes de section doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_section[[i]]) == "numeric",
              msg = "La liste des lignes de section doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_sous_total) == "list",
              msg = "La liste des lignes de sous-total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_sous_total)) {
    assert_that(class(liste_lignes_sous_total[[i]]) == "numeric",
              msg = "La liste des lignes de sous-total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_precision_1) == "list",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_section)) {
    assert_that(class(liste_lignes_precision_1[[i]]) == "numeric",
              msg = "La liste des lignes de pr\u00e9cision doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  assert_that(class(liste_lignes_total) == "list",
              msg = "La liste des lignes de total doit \u00eatre de type list.")
  for (i in 1:length(liste_lignes_total)) {
    assert_that(class(liste_lignes_total[[i]]) == "numeric",
              msg = "La liste des lignes de total doit \u00eatre une liste contenant des vecteurs de nombres entiers.")
  }
  
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(class(avec_titre) == "logical",
              msg = "Le param\u00e8tre avec_titre doit \u00eatre TRUE ou FALSE.")
  
  mes_styles <- creer_liste_style_excel(format = format)
  
  nb_row_to_add <- row_to_add_format(format = format)
  
  formater(classeur = classeur, 
           start_row_tabs = 3 + nb_row_to_add, 
           styles = mes_styles,
           liste_feuilles_avec_note = liste_feuilles_avec_note, 
           liste_type_donnees = liste_type_donnees,
           liste_lignes_titre = liste_lignes_titre,
           liste_lignes_section = liste_lignes_section,
           liste_lignes_sous_total = liste_lignes_sous_total,
           liste_lignes_precision_1 = liste_lignes_precision_1,
           liste_lignes_precision_2 = liste_lignes_precision_2,
           liste_lignes_precision_3 = liste_lignes_precision_3,
           liste_lignes_precision_4 = liste_lignes_precision_4,
           liste_lignes_total = liste_lignes_total,
           liste_unif_unites = liste_unif_unites,
           liste_cellules_fusion = liste_cellules_fusion,
           col_debut = col_debut,
           format = format,
           avec_titre = avec_titre)
}
