# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Geler une(des) ligne(s) et/ou une(des) colonne(s) 
#'
#' Cette fonction permet de geler une ou plusieurs lignes ainsi qu'une ou plusieurs colonnes d'une feuille de classeur
#'
#' @param classeur workbook créé avec openXLSX
#' @param nom_feuille nom de la feuille
#' @param ligne la ligne à geler (0 si pas de ligne à geler)
#' @param col la colonne à geler (0 si pas de colonne à geler)
#'
#' @return Rien n'est renvoyé mais la feuille du classeur est modifiée
#' 
#' @importFrom openxlsx freezePane
#' @importFrom assertthat assert_that
#' @importFrom assertthat is.string
#' 
#' @export
#'
#' @examples
#' 
#' library(openxlsx)
#' library(agreste)
#' 
#' # Création d'un classeur avec une feuille contenant iris 
#' mon_classeur <- createWorkbook()
#' ajouter_tableau_excel(classeur = mon_classeur, tableau = iris, nom_feuille = "iris", ligne_debut = 3, col_debut = 2)
#' 
#' # gel 
#' geler(mon_classeur, "iris", ligne = 3, col = 1)
#' 
#' # Sauver le classeur
#' saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
#' # ouverture
#' browseURL("tableau.xlsx")
geler <- function(classeur,
                  nom_feuille,
                  ligne = 0,
                  col = 0) {
  
  assert_that(class(classeur)=="Workbook",msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(is.string(nom_feuille), msg = "Le nom de feuille doit \u00eatre une cha\u00eene de caract\u00e8re.")
  assert_that(is.numeric(ligne), msg = "La ligne \u00e0 geler doit \u00eatre un entier positif.")
  assert_that(is.numeric(col), msg = "La colonne \u00e0 geler doit \u00eatre un entier positif.")
  
  ligne <- ligne + 1
  col <- col + 1
  
  
  if (ligne != 0 & col != 0) {
    freezePane(classeur, nom_feuille, firstActiveRow = ligne, firstActiveCol = col)
  } else if (ligne != 0 & col == 0) {
    freezePane(classeur, nom_feuille, firstActiveRow = ligne)
  } else if (ligne == 0 & col != 0) {
    freezePane(classeur, nom_feuille, firstActiveCol = col)
  }
}
