# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Lit un fichier
#' 
#' Prend en charge les fichiers csv, xlsx, rds
#' 
#' @param filename CHAR le nom du fichier, extension incluse
#' 
#' @importFrom reader get.ext
#' @importFrom openxlsx read.xlsx
#' @importFrom arrow read_parquet
#' @importFrom readODS read_ods
#'
#' @export
#' 
#' @examples
#' 
#' \dontrun{
#' library(agreste)
#' write.csv(iris, "iris.csv", row.names = FALSE, sep = ",")
#' df <- read_any_file(filename = "iris.csv", header = TRUE, sep = ",", decimal_mark = ".")
#' #'}
#' @return A dataframe
read_any_file <- function(filename,
                          header = TRUE,
                          sep = ",",
                          decimal_mark = ".",
                          sheet = 1) {
  if (isFALSE(file.exists(filename))) {
    stop(paste("Le fichier", filename, "n'existe pas."))
  }
  extension <- get.ext(filename)
  data = switch (extension,
    "csv" = read.csv(file = filename,
                     header = TRUE,
                     sep = sep,
                     dec = decimal_mark,
                     check.names = FALSE,
                     strip.white = TRUE),
    "tsv" = read.csv(file = filename,
                     header = TRUE,
                     sep = sep,
                     dec = decimal_mark,
                     check.names = FALSE,
                     strip.white = TRUE),
    "xlsx" = read.xlsx(xlsxFile = filename,
                       sheet = sheet, 
                       check.names = FALSE,
                       colNames = header,
                       sep.names = " ",
                       skipEmptyRows = FALSE,
                       skipEmptyCols = FALSE),
    "rds" = as.data.frame(readRDS(file = filename)),
    "Rds" = as.data.frame(readRDS(file = filename)),
    "RDS" = as.data.frame(readRDS(file = filename)),
    "parquet" = read_parquet(file = filename,
                             as_data_frame = TRUE),
    "feather" = as.data.frame(read_feather(path = filename)),
    "dataframe" = eval(parse(text = unlist(strsplit(filename, "\\."))[1])),
    "ods" = read_ods(path = filename, sheet = 1, col_names = header,
                     formula_as_formula = FALSE, row_names = FALSE)
  )
  return(data)
  
}
