# WARNING - Generated by {fusen} from /dev/flat_export_excel.Rmd: do not edit by hand

#' Applique des tailles de colonne aux tableaux d'un workbook
#'
#' Cette fonction permet d'appliquer une taille de colonne choisie par 
#' l'utilisateur ou bien automatiquement, 
#' le total étant égal à 83, et les colonnes de texte étant plus larges 
#' que les autres en mode automatique
#'
#' @param classeur Le classeur excel, objet de type workbook
#' @param liste_type_donnees LIST liste de vecteurs contenant 
#' les types de données de chaque colonne
#' @param largeurs LIST liste de vecteurs contenant les largeurs colonne, 
#' "auto" pour appliquer des largeurs automatique
#' @param format CHAR le format de publication : "primeur" ou "chiffres_et_donnees"
#' @param col_debut La colonne à laquelle commencent les tableaux, par défaut 1
#' @param largeur_max LGL si le classeur doit respecter la largeur maximale des 
#' règles de diffusion (83 pour un chiffres et données)
#'
#' @return Rien n'est renvoyé mais le classeur est modifié
#' 
#' @importFrom assertthat assert_that
#' @importFrom openxlsx readWorkbook
#' @importFrom openxlsx setColWidths
#' @importFrom comprehenr to_vec
#' @importFrom collections dict
#' 
#' @export
#'
#' @examples
#' library(openxlsx)
#' library(agreste)
#' 
#' ## Création d'un classeur avec deux feuilles et deux tableaux
#' mon_classeur <- createWorkbook()
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = iris,
#'                       nom_feuille = "iris",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "iris",
#'                       titre = "Données fleurs iris",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "iris",
#'                source = "Ceci est une source quelconque",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = FALSE,
#'                avec_titre = FALSE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "iris",
#'               champ = "France métropolitaine",
#'               format = "primeur",
#'               col_debut = 2,
#'               avec_titre = FALSE)
#' 
#' ajouter_tableau_excel(classeur = mon_classeur,
#'                       tableau = airquality,
#'                       nom_feuille = "airquality",
#'                       ligne_debut = 5,
#'                       col_debut = 2)
#' 
#' ajouter_titre_tableau(classeur = mon_classeur,
#'                       nom_feuille = "airquality",
#'                       titre = "Données qualité de l'air",
#'                       col_debut = 2,
#'                       format = "primeur")
#' ajouter_note_lecture(classeur = mon_classeur,
#'                      nom_feuille = "airquality",
#'                      note = "blablabla",
#'                      format = "primeur",
#'                      col_debut = 2,
#'                      avec_titre = FALSE)
#' ajouter_source(classeur = mon_classeur,
#'                nom_feuille = "airquality",
#'                source = "Eurostat",
#'                format = "primeur",
#'                col_debut = 2,
#'                avec_note = TRUE,
#'                avec_titre = FALSE)
#' ajouter_champ(classeur = mon_classeur,
#'               nom_feuille = "airquality",
#'               champ = "Daily air quality measurements in New York, May to September 1973.",
#'               format = "primeur",
#'               col_debut = 2,
#'               avec_titre = FALSE)
#' 
#' ajouter_titre_primeur(classeur = mon_classeur,
#'                       titre = "Exemple 2022")
#' 
#' taille_colonnes(classeur = mon_classeur,
#'                 liste_type_donnees = list(c("decimal",
#'                                             "decimal",
#'                                             "decimal",
#'                                             "decimal",
#'                                             "texte"),
#'                                           c("numerique",
#'                                             "numerique",
#'                                             "decimal",
#'                                             "numerique",
#'                                             "numerique",
#'                                             "numerique")),
#'                 largeurs = list(c("auto"), c("auto")),
#'                 format = "primeur",
#'                 col_debut = 2)
#' 
#' 
#' ## Sauver
#' saveWorkbook(wb = mon_classeur, file = "tableau.xlsx", overwrite = TRUE)
#' 
#' ## Ouvrir
#' browseURL("tableau.xlsx")
taille_colonnes <- function(classeur, liste_type_donnees, largeurs, format, col_debut = 1, largeur_max = TRUE) {
  assert_that(class(classeur) == "Workbook",
              msg = "Classeur doit \u00eatre un workbook. Lancer un createWorkbook avant de lancer l'ajout de tableau.")
  assert_that(class(liste_type_donnees) == "list",
              msg = "La liste des types de donn\u00e9es doit \u00eatre de type list.")
  for (i in 1:length(liste_type_donnees)) {
    for (j in 1:length(liste_type_donnees[[i]])) {
      assert_that(liste_type_donnees[[i]][j] %in% c("texte", "numerique", "decimal"),
              msg = "La liste des types de donn\u00e9es doit \u00eatre une liste contenant des vecteurs de cha\u00eenes de caract\u00e8re parmi 'texte', 'numerique' et 'decimal'.")
    }
  }
  assert_that(col_debut > 0,
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(is.numeric(col_debut),
              msg = "La colonne de d\u00e9but doit \u00eatre un entier positif.")
  assert_that(format %in% c("chiffres_et_donnees", "primeur"),
              msg = 'Le format doit \u00eatre "chiffres_et_donnees" ou "primeur".')
  assert_that(class(largeur_max) == "logical",
              msg = "Le param\u00e8tre largeur_max doit \u00eatre TRUE ou FALSE.")
  
  sheets <- names(classeur)
  
  indice_feuille <- 0
  
  pao_max <- 83
  weight_num <- 2
  
  for (sheet in sheets) {
    nb_col <- ncol(readWorkbook(classeur, sheet = sheet))
    indice_feuille <- indice_feuille + 1
    assert_that(((largeurs[[indice_feuille]][1] == "auto" | largeurs[[indice_feuille]][1] == 0) | class(largeurs[[indice_feuille]]) == "numeric"),
                msg = paste("Probl\u00e8me dans la colonne Taille_colonnes, tableau ",
                              indice_feuille,
                              ". Veuillez la v\u00e9rifier.",
                              sep = ""))
    if (largeurs[[indice_feuille]][1] == "auto" | largeurs[[indice_feuille]][1] == 0) {
      types <- liste_type_donnees[[indice_feuille]]
      mean_width <- round(pao_max/nb_col, digits = 2) - 0.01
      nb_text <- sum(to_vec(for(type in types) if(type == "texte") 1))
      nb_num <- nb_col - nb_text
      text_width <- mean_width + nb_num*weight_num/nb_text
      if ("texte" %in% types) {
        num_width <- mean_width - weight_num
      } else {
        num_width <- mean_width
      }
      
      d <- dict(keys = c("texte", "decimal", "numerique"),
                items = c(text_width, num_width, num_width))
      
      widths <- to_vec(for(type in types) d$get(type))
    } else {
      widths <- largeurs[[indice_feuille]]
    }
    
    if (format == "chiffres_et_donnees" & isTRUE(largeur_max)) {
      assert_that(sum(widths) <= pao_max,
                msg = paste("La largeur du tableau ne doit pas dépasser ",
                            pao_max,
                            ". Largeur actuelle : ",
                            sum(widths), ", tableau ", indice_feuille, sep = ""))
    }
    
    setColWidths(wb = classeur,
                 sheet = sheet,
                 cols = col_debut:(nb_col + col_debut - 1),
                 widths = widths)
  }
  
}
